### ISSUE TITLE
DXGI

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#103]
Might be worth noting you can have both the DXVK DXGI and WINE DXGI installed. You simply need to pass `WINEDLLOVERRIDES=dxgi=b` to switch to the WINE DXGI for VKD3D functionality according to [Doitsujin](https://github.com/doitsujin/dxvk/issues/883#issuecomment-456883972).  It'd be nice to have both to avoid having 2 different builds installed when its not necessary since we can easily add the override on a per game basis at the command line or in Lutris' override list.

**Comment by Tk-Glitch** [comment]
Except that won't work with our winelibs (making DXVK effectively builtin). You can install DXVK as native libs but that's up to you and not an option proposed by wine-tkg. As a side note, DXVK winelib is not available in any of the lutris builds.

**Comment by ronoverdrive** [comment]
> Except that won't work with our winelibs (making DXVK effectively builtin). You can install DXVK as native libs but that's up to you and not an option proposed by wine-tkg. As a side note, DXVK winelib is not available in any of the lutris builds.

Ok and since DXUP requires the DXVK winelib we have no choice but run separate builds for VKD3D if we also want DXUP.

*shakes fist at the sky* Damn you Cake! We can never have and eat you too!! ;P j/k

**Comment by Tk-Glitch** [comment]
DXUP doesn't require DXVK winelib. It'll work just fine with external DXVK. Also, external DXUP would work as well.

**Comment by Tk-Glitch** [comment]
The winelib way enables a full replacement of wine's implementations, so you don't have to rely on overrides. It's not a requirement to use them,  and it's simply offered as an option because of how specific it is. While it might be hard for the common user to build DXVK or DXUP winelibs and inject that into a wine build, it's easy to download a prebuilt dll. So I'm providing a solution to ease the hardest way because there are plenty of easier ones users can follow by themselves :D The lutris switch is definitely not something I'm trying to replace here.

**Comment by Tk-Glitch** [comment]
Building all winelib'd for DXVK+DXUP+VKD3D's glory without using DXVK's DXGI, and only using that one as an override sounds good for such needs. But I can't reasonably provide such solution in wine-tkg-git PKGBUILD directly as that would mean mingw dependency to build DXVK's DXGI. I'll have to think about it.. @Joshua-Ashton Maybe some kind of https://froggi.es based solution..
