### ISSUE TITLE
How can I use your builds with Ubuntu?!

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#107]
I always use your releases with Manjaro, but I can't use Manjaro, because it is not stable right now after the last updates, so I decided to use Kubuntu 18.10, but I can't figure out how to use your releases with Ubuntu?

**Comment by Tk-Glitch** [comment]
I assume you're talking about the prebuilt pacman packages? You can't use them as-is, because you'd need pacman and Ubuntu doesn't use that.
You could probably extract it to some folder and launch it externally though, or put it in the Lutris runners if you're using lutris. You can also rely on Lutris prebuilts directly as they are made using wine-tkg-git generated sources, then built on Ubuntu.

**Comment by ahmed-elsayed2017** [comment]
On manjaro, I can edit customization.cfg to choose what to add and what to remove, and the default settings miss 4 important things to me that I want to add like: gallium_nine, FS_bypass_compositor, proton_fs_hack, and plasma_systray_fix.

**Comment by Tk-Glitch** [comment]
Well, this is a pkgbuild for makepkg, that creates pacman packages. So obviously you'll only get all the options on a distro that supports makepkg/pacman.

The "protonified" build from Lutris comes with `FS_bypass_compositor` and `proton_fs_hack`. You can use nine standalone https://github.com/dhewg/nine with it. But yeah, you'll still miss plasma_systray_fix.

**Comment by ahmed-elsayed2017** [comment]
I can't find protonified build for 4.0 in Lutris. I will use https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3 for Gallium because I use Obiaf ppa.

**Comment by Tk-Glitch** [comment]
The source is up, but Strider didn't build it as of yet.
