### ISSUE TITLE
DXVK missing deps

### ISSUE THREAD

**Issue by random2324** [Tk-Glitch/PKGBUILDS#11]
Thanks for providing this fantastic package!
Very unfortunate to fail after building wine because it fails to build dxvk.

glslang
mingw-w64-gcc

Also is there a way to checkout the current PKGBUILD without using svn export? As svn states there is no working directory, which means there is no .svn or .git so you cannot use svn checkout.

**Comment by Tk-Glitch** [comment]
I'm glad you find it useful :)

DXVK building should be fixed with https://github.com/Tk-Glitch/PKGBUILDS/commit/60ceb6bbe5d91207d61f9671aa6eff638077d75e

I have only added glslang as a dependency because winelib builds don't require mingw-w64-gcc and are using wine-gcc instead. Though that means you need to have wine already installed to be able to build winelib DXVK. I should add a note about that somewhere.

For your second issue, I think the easiest way would be to git clone the PKGBUILDS tree. Not ideal though, I know. I'll think about it.. Maybe a script, or maybe just move the wine pkgbuild elsewhere.

**Comment by random2324** [comment]
Thx for the fix.
I didnt know about the possibility to let wine compile DXVK.
I wonder why the DXVK-git PKGBUILD in AUR relies on mingw then, since its an enormous dependency.

Yeah, would be nice to git clone your repo!

**Comment by Tk-Glitch** [comment]
There are currently four "ways" to compile DXVK with :

1. Mingw-w64 on linux
2. Winegcc on linux, through wine - that's what my pkgbuild is using (proton as well, maybe only for 64-bit binaries though)
3. Mingw-w64 on windows
4. The windows version of mingw-w64 on wine, on linux

The 1st is the "slowest" performing binary, while the 2nd is the fastest, 3rd and 4th performing equally and close to the 2nd. This is the default way to build DXVK and what's used to compile the "official" DXVK releases binaries.

The 2nd is the fastest binary. This one is neat in various ways.
As you noticed, it doesn't require the big dependency that mingw-w64 is and will use your system GCC instead, passed-through by winegcc.
These builds don't statically link libstdc++ resulting in the smallest binary, and since they are winelibs, they'll also bypass the vulkan loader and associated overhead.
But (because there's one), they are having an issue with address space that makes it crash-prone on 32-bit games, for a reason we don't know yet.

3rd and 4th are performing equally good. They do require DXVK source modifications and are the most annoying to setup, but result in the best performing binaries all-around. It's close to the 2nd perf-wise yet without that address space issue.

The perf offset between the builds is most noticeable on 32-bit games. On 64-bit games the difference is usually small, or even unnoticeable depending on the game/hardware used.

You can git clone git@github.com:Tk-Glitch/PKGBUILDS.git
