### ISSUE TITLE
mtga patch doesn't help

### ISSUE THREAD

**Issue by truf666** [Tk-Glitch/PKGBUILDS#111]
https://github.com/Tk-Glitch/PKGBUILDS/blob/ebe4fca31ee56dd0896c850154bd03c09147a9b2/wine-tkg-git/wine-tkg-patches/mtga.patch#L10

It seems 1000 isn't enough for my machine. I've tried 1000000 - that solves updater problem for sure.

**Comment by Tk-Glitch** [comment]
There has been some talk recently about that. https://bugs.winehq.org/show_bug.cgi?id=45546
Instead of extending the window to absurd values, removing it altogether would be a more universal workaround. I bet your hardware isn't the slowest possible :D
That being said, both solutions are ultimately bad as they will prevent threads to suspend. I'll have to think about it and I'd really like to find a better solution.

**Comment by Tk-Glitch** [comment]
Yeah, Lutris users would be completely fine with that. I'll have to disable the patch for my own build though :frog:

**Comment by Tk-Glitch** [comment]
@truf666 I'd be really grateful for some feedback on that one, thanks :)
