### ISSUE TITLE
BattlEye patches by @Guy1524

### ISSUE THREAD

**Issue by mkljczk** [Tk-Glitch/PKGBUILDS#12]
These patches are probably work in progress, but could you add them to wine-tkg?
[stable branch](https://github.com/Guy1524/wine?files=1)
[unstable(?) branch](https://github.com/Guy1524/wine/tree/battleye-work?files=1)

**Comment by Tk-Glitch** [comment]
I *could* but they are VERY experimental and indeed WIP. They are not working so far btw. One game works because it doesn't care about BE crashing later on, but that's about it. It also breaks a shitload of stuff (i.e. other games) and isn't compatible with wine-staging.
It's clearly not ready for the show even though it's promising.

At this stage, you should probably give the user patching features of the PKGBUILD a go.
When it'll be closer to a working state, it'll be added for sure.

I'm following Guy1524's work on discord in spite of me anyway :D

**Comment by Tk-Glitch** [comment]
If Guy1524 ends up working more on BE/EAC and it's pending for a merge, I'll add community-patches. Keeping this issue open doesn't make too much sense anymore :D
