### ISSUE TITLE
Divinity Original Sin 2: DE fails to launch silently on proton-tkg 4.5+ (works on tkg 4.4- or vanilla)

### ISSUE THREAD

**Issue by clapbr** [Tk-Glitch/PKGBUILDS#153]
Any idea what could it be or the culprit change, thought it could be proton 4.2 vs 3.16 but vanilla proton 4.2 also works fine? Normal logs shows it silently launching then exiting, proton logs are a bit too noisy to understand wtf is going on also :P Taking suggestions on how to provide more clues than this. 
[steam-435150.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3040653/steam-435150.log)

**Comment by Tk-Glitch** [comment]
It might not be the breaking point but it seems to freak out on :
```
10869.967:0038:0071:warn:module:process_attach Initialization of L"nvcuda.dll" failed
```
You may want to try turning on nvapi in the problematic proton-tkg build's `user_settings.py` file in `~/.steam/root/compatibilitytools.d/Proton-tkg*`.
Else it might be worth giving it a try in winesteam and see how regular wine fares. It could be a regression.

**Comment by clapbr** [comment]
First I tried switching the nvapi and no luck. Then I decided to rebuild my system wine which was still 4.4 and then proton-tkg and now it'´s working. Could system wine be interfering with proton somehow? Or something got fixed by you or upstream. In any case, I want to game a bit :frog and won´t mess with what's working so feel free to close this if you think it´s not worth bothering/investigating.

**Comment by Tk-Glitch** [comment]
Something quite important was changed indeed. By default, DXVK will now be downloaded as prebuilt from the latest release on Github instead of building current master as winelib as it was before. The option is still there, but it's no more default.

Considering the various issues winelib DXVK can create, it was probably linked to your problem if you were using default settings.

Other than that, no reason for system wine to interfere.
