### ISSUE TITLE
TK with Nvidia Beta

### ISSUE THREAD

**Issue by tr37ion** [Tk-Glitch/PKGBUILDS#182]
Is it possible to make this compatible with eg. `nvidia-beta-all` AUR, too? TRying to install it in a 
```
pacman -Qs nvidia beta
local/lib32-nvidia-utils-beta 430.09-1
    NVIDIA driver utilities and libraries (beta version) (32-bit)
local/lib32-opencl-nvidia-beta 430.09-1
    NVIDIA's OpenCL implemention for 'lib32-nvidia-utils-beta'
local/nvidia-beta-all 430.09-1
    NVIDIA drivers for all kernels on the system (beta)
local/nvidia-libgl-beta 430.09-1
    NVIDIA driver library symlinks for 'nvidia-utils-beta'
local/nvidia-utils-beta 430.09-1
    NVIDIA driver utilities and libraries (beta version)
local/opencl-nvidia-beta 430.09-1
    NVIDIA's OpenCL implemention for 'nvidia-utils-beta'
```

environment sresults in

```
==> Making package: wine-tkg-staging-esync-nine-dxvk-faudio-marchopt-lutris-git 4.7.r6.g7d9b7bbd-155 (Do 02 Mai 2019 14:59:45 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
:: There are 2 providers available for lib32-libgl:
:: Repository multilib
   1) lib32-libglvnd  2) lib32-nvidia-340xx-utils

Enter a number (default=1):
resolving dependencies...
looking for conflicting packages...
:: lib32-libglvnd and lib32-nvidia-utils-beta are in conflict. Remove lib32-nvidia-utils-beta? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: lib32-libglvnd and lib32-nvidia-utils-beta are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
==> WARNING: Failed to remove installed dependencies.
```
because of dependency issues with ` lib32-libglvnd` and `lib32-nvidia-utils-beta`. Is there a way to make this compatible somehow?

**Comment by Tk-Glitch** [comment]
The best way would be to get the nvidia-beta-all maintainer to fix his stuff. It's been one of the reasons I made the nvidia-all PKGBUILD. Not providing libgl and conflicting with libglvnd is a completely broken setup. This package is not sane and shouldn't be used.

**Comment by Tk-Glitch** [comment]
You could also remove the libglvnd dependency in the PKGBUILD as a workaround, but you get to keep the pieces if anything breaks :frog:

**Comment by tr37ion** [comment]
I got it working. Removing the AUR `nvidia-beta-all` packages. Reinstalling the "normal" `libglvnd` package needed by your package and then installing your `nvidia-all` PKGBUILD with `makepkg -sri` and it works fine so far :)

**Comment by Tk-Glitch** [comment]
Glad you got things to work as you wanted :) Enjoy!

**Comment by Det87** [comment]
@Tk-Glitch What do you mean "not providing libgl". The driver (nvidia-beta-all) is not supposed to provide the libs (nvidia-utils-beta & split friends). That's how you _also_ do it.

Libglvnd provides/conflicts was to sync with the Nvidia blob one (beta vs. stable). It's since got to lag behind a bit, so apparently a non-issue.

**Comment by Tk-Glitch** [comment]
@Det87 
What I meant is that `libglvnd` provides `libgl`. So if the package is conflicting with/providing `libglvnd` without providing `libgl` as well, something is wrong.

The Arch package **depends on** `libglvnd` and doesn't provide it, and I'm doing it that way as well.
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/nvidia-utils

However, `lib32-nvidia-utils-beta` as you linked it **provides** `libglvnd` (lib32 in that case, but that's not my point) and conflicts with it. Yet the package doesn't provide `libgl`. So you very logically get that unresolvable conflict above as replacing `lib32-libglvnd` with `lib32-nvidia-utils-beta` breaks the `libgl` dependency.

I hope I'm being clearer, this can get confusing fast :frog:

**Comment by Det87** [comment]
@Tk-Glitch no, that's the `nvidia-libgl` "transitionary" package (before we had `libglvnd`). There's not much difference with `nvidia-utils` providing the `libglvnd`, and `nvidia-libgl` be the symlink dummy `libgl`-provider.

But sure, leaving libglvnd to "offload" (or whatever it's doing) Nvidia's functionality to its native libs without conflicts & version mismatches seems to work like intended.

Offnote, it's great that things evolve, but due to these constantly maintainatory burdenly evolutionary reasons, I finally left Arch after like total first-use-last-use period of 9 years or so. Not even the current maintainer (a TU) has had the motivation to fix it.
