### ISSUE TITLE
Very slow performance

### ISSUE THREAD

**Issue by Jordi234** [Tk-Glitch/PKGBUILDS#194]
Hi!
I'm building this wine-tkg for some days and now, when I try to use wine with my Lutris games, it runs VERY slow. With 4.6-staging version (I think) all worked very fast and well, it was a great difference with the bulids that Lutris offers....what i'm doing bad?
I'm using an AMD A6 and NVidia 710, is not the best pc for gaming but I'm using very old games, and all run good with Lutris builds.
I don't touch the config file (I'm a noob).
Thank you.

**Comment by skeevy420** [comment]
I'd start by building it with 4.6 staging (go to the line _staging_version="" in the cfg and change it to _staging_version="v4.6") and see if that fixes any problems you might have. If it does, go forward a commit at a time until the problem does occur (use the commit hash in the version line).  I've had to limit my builds to specific versions when odd stuff pops up.

Since that's an APU with a dedicated GPU, you might want to try setting _launch_with_dedicated_gpu="false" to "true".

When building from git, sometimes you just might sync and build at the wrong time which can cause odd issues to arise.  Is this a case of that?

**Comment by HengiFettlich** [comment]
another suggestion might be to build with d9+dxvk.

**Comment by Jordi234** [comment]
Well, I dont remember exactly the version, I tried with staging 4.7. All is working imprsionately fast, but EA Origin and Epic Games Store dont works, with "Protocol error: process 0008: sendmsg: Bad file descriptor" and "Unable to read stat for process".
Sorry, I'm very noob here and I can't understand what you say "go forward a commit at a time until the problem does occur (use the commit hash in the version line)", and "When..sync and build at the wrong time...", I only made a "git pull origin master" to update and then "makepkg -si".
Thanks!

**Comment by skeevy420** [comment]
Commit at a time would be to go to [wine staging's commit history](https://github.com/wine-staging/wine-staging/commits/master) and use the commit hash for _staging_version="" in wine-tkg-git/customization.cfg

I also 2nd the d9+dxvk suggestion.  I've been using them w/o problem* since at least wine 4.0.

Also, a little over a month ago _stg_shared_mem_default="false" changed from "true" to "false" due to reported issues with Origin.  If you've been editing the profiles directly for whatever reason, you might want to check and see if there was a merge conflict of some kind.

Also, wik, I did a quick Google search before commenting and it shows that the error you're getting is due to esync being enabled...one of the Proton fixes was to increase systemd's DefaultLimitNOFILE.  How to do that is in [ esync's README ](https://github.com/zfigura/wine/blob/esync/README.esync)

*aside from the occasional patch or Wine breakage.

**Comment by skeevy420** [comment]
Commit at a time would be to go to [wine staging's commit history](https://github.com/wine-staging/wine-staging/commits/master) and use the commit hash for _staging_version="" in wine-tkg-git/customization.cfg

I also 2nd the d9+dxvk suggestion.  I've been using them w/o problem* since at least wine 4.0.

Also, a little over a month ago _stg_shared_mem_default="false" changed from "true" to "false" due to reported issues with Origin.  If you've been editing the profiles directly for whatever reason, you might want to check and see if there was a merge conflict of some kind.

Also, wik, I did a quick Google search before commenting and it shows that the error you're getting is due to esync being enabled...one of the Proton fixes was to increase systemd's DefaultLimitNOFILE.  How to do that is in [ esync's README ](https://github.com/zfigura/wine/blob/esync/README.esync)

*aside from the occasional patch or Wine breakage.

**Comment by Jordi234** [comment]
I tried to build the same 4.7 with d9+dxvk and I can hear the games sound but with black screen...
I tried to set  _stg_shared_mem_default="true" and I can't play Origin too. I don't know what more I need to do.
With 4.7 if works is ok, no more things I need to do, works very well.

**Comment by rphsoftware** [comment]
Its all them frogs :frog:

**Comment by Jordi234** [comment]
Now I building with lutris profile....with tkg-4.7 in Lutris works perfectly.

**Comment by Jordi234** [comment]
It works with lutris profile. 
Problem solved.
Thank you for the help!!!
