### ISSUE TITLE
4.8_gamepadregression.myrevert fails at applying

### ISSUE THREAD

**Issue by fosspill** [Tk-Glitch/PKGBUILDS#202]
Hi!

The 4.8_gamepadregression.myrevert patch fails at applying with the ffxiv profile.

**Comment by skeevy420** [comment]
AFAICT, it broke with a staging update a few days ago.  I noticed it during my test compiles when working on the optimization patches.  If you set staging back to v4.8 (or find the exact commit where it breaks and use the one before it) it'll work as a temporary fix until someone actually takes a look at it (what I've been doing since I'm busy with other things).

I'm actually about to start a compile due to the latest dxvk release and I'll use the patch to intentionally break my build and see if it isn't something I'm able to fix.

**Comment by skeevy420** [comment]
Found them.  Revert to these commits to "fix" the failing patch for the time being.

_plain_version="042e0625695a82aa71ddf825c693680d5d8aa0dd"

_staging_version="1b7ebd3bb8b7fc6fa3347da8de4fc528c89adc38"

**Comment by Tk-Glitch** [comment]
The patch was updated with https://github.com/Tk-Glitch/PKGBUILDS/commit/459a1e6eea4c2432c06ab00633f54308449f2ba5
