### ISSUE TITLE
Questions about virtual refresh rate patch

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#208]
I was setting up the configs for some dxvk and vkd3d proton builds and I became curious when I was looking at the suggested values for the refresh rate patch and thought about the values that my TV supports.

Does it support using float values like 59.94?

Does it support using less than 60, like 50 for older PAL stuff?

Would using a value like 30 cap a game or program to 30fps?

**Comment by aufkrawall** [comment]
@Tk-Glitch Would it be possible to change the patch in that regard that the default 60Hz are not always included? I never use 60Hz, so it doesn't make sense for my setup that this value is always offered regardless.

**Comment by skeevy420** [comment]
> @Tk-Glitch Would it be possible to change the patch in that regard that the default 60Hz are not always included? I never use 60Hz, so it doesn't make sense for my setup that this value is always offered regardless.

It's Wine that's 60hz by default.  You'd have to file a bug report with Wine to get that changed.

The patch allows changing the Wine default to your preferred default by changing 60 to 999999 in Wine's source and then seding the 999999 to what you define in the config (it's either that or create a patch on the fly).  

It's also an int so float values won't work.

**Comment by Tk-Glitch** [comment]
@aufkrawall Does this patch have any effect for you to begin with? Keep in mind it doesn't change display mode at all.
@skeevy420 For me it does absolutely nothing (as expected) independently of the value used, so I can't speak about non-existing behavior.

**Comment by skeevy420** [comment]
That's how it's been for me.  Was just curious if it could be used as a hacky frame limiter...like a jury-rigged libstrangle.  So far it hasn't done that for me so I don't think it'll work like that manner.

**Comment by aufkrawall** [comment]
@Tk-Glitch Yes and no. :)  Since I just use 73Hz (would be 75Hz if AMD driver didn't flicker..) without FreeSync, it doesn't really matter that the Proton upscale hack reports just 60Hz, as vsync still works correctly with 73fps@73Hz.
But I got a weird issue with lowered performance in Heroes of the Storm after alt + tabbing the game (I work around it by switching virtual desktops). When I add 73Hz to the fake refreshrate list, I however am always stuck with the lowered performance, even without alt + tabbing. So be it coincidence or whatever, but there seems to be some kind of connection.

Or perhaps not, as there is also that performance penalty with plain wine-vanilla. It however shows some weird resolution switch behavior when alt + tabbing (despite of the display's edid just providing one resolution with one refreshrate). Admittedly, this sums up to a really high level of weirdness...

**Comment by Tk-Glitch** [comment]
Interesting.. Does it happen independently of the display mode (fullscreen/windowed/borderless)?

**Comment by skeevy420** [comment]
What kind of GPU do you have?

I don't know about a lot of that since my "monitor" is a 49" 60hz 1080p TV, but have you tried setting `/sys/class/drm/card0/device/power_dpm_force_performance_level` to high?  That was one of the flicker fixes back in the day for me with my last AMD GPU on this same TV and my previous TV.  

At one time my fix for that was a script with three lines -- the shebang line, and echo high line, and an echo auto line.  Seriously, that fixed my flickering...haven't needed it since kernel 4.15.something.  It would bug up and start in low, but going from low to auto didn't help, going low>high>auto did.  Weird little bug there.

Currently running my RX 580 4G with that set to manual from my WattmanGTK systemd service (I'll share the basic units and give instructions on how to use it if that's something you need) that undervolts the hell out of my GPU since it runs really freakin hot by default which causes all sorts of dumbass, weird issues...you should keep an eye on your GPU temps and see if you're not getting any thermal throttle flicker like my 580 got before undervolting...ditto with my previous 260x as well, but that was before ppfeaturemask so my only option there was to not push games to their limits...played a lot of stuff at 30fps, low to medium settings with that card...  

I know it's anecdotal, but undervloting, making an xorg conf with damn near all default settings (force enabling vsync is the only difference), and a stupid long kernel command line (apparently with conflicting values; thanks, Manjaro amdgpu-experimental package) are the only GPU tweaks I do.  

For some reason, I've found that force enabling vsync in 20-amdgpu.conf helps with a lot of my screen tearing problems on KDE regardless of what vsync setting I use within KDE.

**Comment by skeevy420** [comment]
> Interesting.. Does it happen independently of the display mode (fullscreen/windowed/borderless)?

For me it was almost always caused by thermal throttling and it didn't matter what was going on.  The 580 would stabilize and go back to normal once it cooled down whereas my 260x needed a reboot to stabilize once it cooled down.  Since the 580 has access to ppfeaturemask, I experimented with undervolting to lower the temps and that fixed all of my problems.  

The 260x eventually got that, but mine was dying by then so it was a fruitless endeavor trying to low-voltage fix it.  By then my only fix was new hardware.  It was a 6 or 7 year old card that I ran hard.

Before that it was just caused by issues in the early AMDGPU days when DPM was first being implemented and required a hacky workaround for a few kernel versions.  Some AMDGPUs are still affected by that like the 280/380s, some Raven Ridge APUs...usually when the card is pushed to it's limits over 60hz based on posts I've read and the dpm high tweak has mixed results with them.

**Comment by aufkrawall** [comment]
> Interesting.. Does it happen independently of the display mode (fullscreen/windowed/borderless)?

I could reproduce it for weeks and checked a week ago the last time - now I can't reproduce. I'm suspecting recent DXVK changes, but can't say for sure. It happened both with fullscreen and borderless.
There was an additional issue regarding extremely slow window switching when alt + tabbing + dxvk + esync, which made me stick to borderless. It however seems that was caused by using the recommended file descriptor limit values for esync instead of systemd's increased default values since version 240.

So, as of now, everything seems to be fine (except wine-staging apparently introducing regressions for Blizzard games):
https://bugs.winehq.org/show_bug.cgi?id=47265

**Comment by aufkrawall** [comment]
I applied the patch by Andrew Wesie to fix the Blizzard games crashes with 4.9 and tried again with a fake refreshrate of 73Hz: The performance penalty is indeed gone. :)

**Comment by skeevy420** [comment]
> I applied the patch by Andrew Wesie to fix the Blizzard games crashes with 4.9 and tried again with a fake refreshrate of 73Hz: The performance penalty is indeed gone. :)

Awesome. 

Now if only 74+hz worked for you.  Hopefully AMD will get that figured out.

Want me to close this?

**Comment by aufkrawall** [comment]
No objections from my side. :)
Btw. sorry for hijacking your ticket. :frog:

**Comment by skeevy420** [comment]
Not a problem, they're related to the same thing.

**Comment by aufkrawall** [comment]
I always had the gut feeling that there was still evil lurking: Turns out this likely was caused by`dxvk-mingw-git`, but not `dxvk-winelib-git`. Using default compile flags, wth is going on?
Hm, maybe something's odd with the -bin packages of mingw which I used. Going to check out the official DXVK binaries provided by doitsujin.
