### ISSUE TITLE
cable error

### ISSUE THREAD

**Issue by logan001** [Tk-Glitch/PKGBUILDS#209]
Every time i start Guild Wars 2 (with d9vk) that is set to 120 MHz refresh rate (in game) i'll get an error on monitor to use the cable that came with the monitor.
this does not happen with the same game/refresh/driver in linuxmint
monitor is set to 120MHz with xrandr. the monitor can go up to 144 MHz.
does the building process change anything to refresh rate?

**Comment by skeevy420** [comment]
Have you tried or did you set the virtual refresh rate patch to 120?  Apparently Wine expects or is hardcoded to use 60, but Tk-Gltch includes a patch to change that.  It's really close to the very bottom of the config and one of the last patches available.

My monitor is limited to 60 and lower, see my issue below, so this isn't an issue I can even experience or bring upon myself.  Since you didn't mention that patch I thought that it might be worth trying.

Since I don't have the hardware nor have I even looked into this before, that's all the help I can give.

**Comment by logan001** [comment]
i haven't build wine. i just use lutris which supposedly has tk-wine. sine both linuxmint and arch use the same version of wine/nvidia drivers (at least the in theory) they should both work or manifest the same.
sorry i forgot to say one little very important thing: i think its nvidia driver build. not the wine.
i had previously use an aur script and a week ago i found about this repo and since it has "everything" i decide it to build the newer beta driver (05 not 07. i use to have 02). and thats when monitor error started to appear.

**Comment by skeevy420** [comment]
Not an Nvidia user (RX 580 myself), but I'd either go back to the current stable or try the 07 beta and go back to stable if that doesn't work.  Sounds like you got hit with a random beta bug.  It happens.

As a Manjaro user, I build all of my Wine packages for Lutris over using what they provide.  Given the option, I prefer running stuff that's either compiled myself or included in my distribution's repositories than using software compiled on a different Linux version that _should be_ universal.

**Comment by Tk-Glitch** [comment]
@logan001 It might be related to the patches I'm using to extend kernel compatibility further than what nvidia provides. What kernel version are you using btw?

**Comment by logan001** [comment]
on arch i have tried both 5.1.4-1-ck-zen and 5.1.4-arch1-1-ARCH and both have same behavior
on mint i have 5.0 (from distro). no problem there. but of course driver works with 5.0 by default.

**Comment by Tk-Glitch** [comment]
I can't reproduce your issue on my end with DVI or HDMI (I don't have a DP display to test). I would give 430.14 a try as it doesn't require the hacky patch that might be responsible for your issue. It comes with the `VK_EXT_host_query_reset` extension DXVK can make use of and has been performing well (better than 418.52.05, apparently). If you end up facing the same issue with 430.14, then it's unrelated and it might be some weird 5.1 kernel issue.

**Comment by logan001** [comment]
i've installed 430.14. the problem is still there. i also use wine stagging (from arch) and the problem is still there.
i remove d9vk and the issue is not present anymore. BUT when i change the refresh rate in game will not change the refresh rate of the monitor. so that sort of explain why the bug is not there. so it might be kernel or kernel+d9vk (vulkan).

**Comment by skeevy420** [comment]
Are you using a point release of d9vk or building from git master?  If point release, try building it from master since there was a [commit](https://github.com/Joshua-Ashton/d9vk/commit/b1ce57c42cde01d8c99a14cf7cac5e1da4819d5d) a few days ago that looks like it might help.

For cable irony, went to charge my phone yesterday with the factory cable and charger and my phone informed me it wouldn't fast charge on non-factory chargers or cables.  

Went old-school, blew it all out like it was an NES with Mario/Duck Hunt and it worked just fine.

**Comment by logan001** [comment]
i just download 74f89222e419cb70ce436ed4397018f224b21dd4 this morning and i still have the same problem.

**Comment by Tk-Glitch** [comment]
If you also get the issue on 430.14 it means it's not related to nvidia-all. It could very well be D9VK (Josh has faced various res sorting issues lately and it sounds interestingly related..). It might also be a bug in nvidia drivers, kernel 5.1, or the interaction between the two as you said it didn't happen on 5.0. Did you use the exact same D9VK version on 5.0 and 5.1 btw? If you didn't it might be worth a shot to validate the D9VK bug theory.

**Comment by skeevy420** [comment]
I concur.  Take everything back to the last good working setup and update things one at a time until the bug happens -- kernel 5.0, Nvidia stable, D9VK 0.11 release, and possibly even back to Wine-Staging 4.7r11 or earlier since it's been a little finicky since 4.7r12ish.

First test the downgrades.  If good, then update D9VK stable to master and test.  If good, then try the updated Nvidia driver with the 5.0 kernel.  If good, then update kernel 5.0 to 5.1.  If good, cool, problems been fixed somewhere, if not, it's probably the kernel to blame...or you could start playing with Wine releases and see if one of them does the trick (I'd personally test 4.7r11 & 4.9r3 because I've had and am having good results with those and had "lots-o-fun" during the 4.8 staging series).

It's a pain in the ass, but it's what I would do if I was trying to track down an oddity like this.  Based on your replies, my guess is it's likely the driver/kernel combination, maybe D9VK, less-likely is Wine.

Catalyst used to be like this back in the day before we had AMDGPU. We'd be stuck on old kernels and Mesa versions for long periods of time and community patches like what Tk-Glitch is providing here had similar results in that they'd work for some and not for others.

**Comment by logan001** [comment]
i didnt try your suggestion but i just created a new lutris prefix with same wine/d9vk/settings on linuxmint (where i had no problem) and the new game prefix will have the same issue while the older prefix still works.

**Comment by Tk-Glitch** [comment]
Interesting.. So it looks like wine or d9vk regressed. I have had no issue with my 120Hz monitor myself, neither with wine nor d9vk, but it would be great to find the actual culprit. Does it happen without d9vk? Does it happen with an older d9vk build?

**Comment by logan001** [comment]
not really. as i said i use the same wine version from lutris on both prefixes. and the new one has the problem. the old one works without an issue. does it matter if i created while i had a different kernel?

**Comment by Tk-Glitch** [comment]
Nah, doesn't matter.

**Comment by Tk-Glitch** [comment]
Is it still an issue?

**Comment by logan001** [comment]
yeap.
i really have no clue why only that profile is not giving any problems to the monitor.
i've tried to build wine from here and i still have the same issue.

**Comment by Tk-Glitch** [comment]
Someone else encountered a similar issue over our discord. The fact that it only happens with D9VK and not wined3d nor DXVK clearly indicates (once more) a D9VK issue is likely. The fact that it works on some old prefix and not newer ones is mysterious though. Getting some logs and notifying Josh about it is probably the best you can do about it right now (https://github.com/Joshua-Ashton/d9vk/issues). I am still 100% unable to reproduce the issue on my end.

**Comment by logan001** [comment]
ok.
thank you

**Comment by Faalagorn** [comment]
Was it me on Discord? I saw similar issue with Minecraft Story Mode (D3D9Ex game) which worked for me previously, though I think it happened for wined3d too… Either way, it stopped for me at one point with one of my proton-tkg upgrade and although the game still won't start it doesn't make my monitor "crash" now.

I'm using RADV and my main monitor is connected through HDMI.
