### ISSUE TITLE
I have mingw-w64-gcc

### ISSUE THREAD

**Issue by SolarAquarion** [Tk-Glitch/PKGBUILDS#234]
`mingw-w64-gcc /usr/bin/x86_64-w64-mingw32-cc`

 silly me, you didn't add mingw-w64-gcc as a makedepend therefore aurutils and similar things doesn't pick it up

**Comment by Tk-Glitch** [comment]
Mingw is a very weird and terrible dependency as it requires a specific process to get a working install going on Arch right now, and that's why I decided against adding it to makedepends. I am providing an automation script to fix the problem using the AUR packages available (with a little patch for a free +30% perf on 32-bit DXVK/D9VK). Hopefully it'll get re-added to the community repository soon-ish.

**Comment by SolarAquarion** [comment]
i use aurutils to build the package so i get a nice clean "chroot"

**Comment by Tk-Glitch** [comment]
1 - What's your issue?
2 - mingw is part of the optional dependencies - because it is an optional dependency.
3 - If aurutils doesn't respect optdepends, well, that's an aurutils issue.

**Comment by SolarAquarion** [comment]
it respects optdepends only if you include it as a makedepend

**Comment by Tk-Glitch** [comment]
Well then it breaks a truckload of how wine building process works (outside of the scope of my PKGBUILD). I won't be supporting that.

**Comment by SolarAquarion** [comment]
thanks

**Comment by SolarAquarion** [comment]
i'll just install mingw-w64-gcc to my chroot

**Comment by Tk-Glitch** [comment]
When/if wine ends up requiring mingw for compilation, I'll add it as makedep (we'd need an official Arch package for that, still). Currently it's not the case and is optional.
You are supposed to get working wine builds without it and if that's in your book, to report issues you encounter on such builds to winehq. However there has been gamebreaking bugs and regressions lately (since 4.9) related to that "novelty", so I can completely understand the desire to use what works the most reliably currently.

Since mingw-w64-gcc isn't in Arch repos, adding it to makedepends would break for anyone who don't already have the package installed and isn't using a specific tool to find AUR deps. Even then, it would likely be broken due to its nature and installation quirks.
So you might get a broken setup with that anyway if you end up adding it to makedepends by hand.

I don't have a clean solution to offer for aurutils and the way wine grabs optionals at build time. It would require either rewriting parts of aurutils or wine, unless there's a better way I can't see.

If someone has an non-terrible idea I'm open to suggestions.

**Comment by SolarAquarion** [comment]
I'm just going to do "arch-nspawn $CHROOT pacman -S mingw64-gcc" and be
done with it

**Comment by SolarAquarion** [comment]
i'll just install mingw-w64-gcc to my chroot which works for my purpose, especially since aurutils generates a "repo" on my local drive
