### ISSUE TITLE
Error building kernel 5.2

### ISSUE THREAD

**Issue by Jordi234** [Tk-Glitch/PKGBUILDS#241]
Hi! I'm trying to build the 5.2 kernel and I can't. I used all the default options. Here is the error:
`arch/x86/kernel/hpet.o: warning: objtool: hpet_disable()+0x63: can't find jump dest instruction at .text+0xfa5
  CC      arch/x86/kernel/amd_nb.o
arch/x86/kernel/amd_nb.o: warning: objtool: amd_get_mmconfig_range()+0x37: can't find jump dest instruction at .text+0x779
  CC      arch/x86/kernel/kvm.o
  CC      arch/x86/kernel/kvmclock.o
  CC      arch/x86/kernel/paravirt.o
arch/x86/kernel/paravirt.o: warning: objtool: native_set_ldt()+0x45: can't find jump dest instruction at .text+0x35f
  CC      arch/x86/kernel/paravirt_patch_64.o
  CC      arch/x86/kernel/paravirt-spinlocks.o
  CC      arch/x86/kernel/pvclock.o
  CC      arch/x86/kernel/pmem.o
  CC      arch/x86/kernel/jailhouse.o
arch/x86/kernel/jailhouse.o: warning: objtool: jailhouse_paravirt()+0x87: stack state mismatch: cfa1=7+72 cfa2=7+64
  CC      arch/x86/kernel/pcspeaker.o
  CC      arch/x86/kernel/pci-swiotlb.o
  CC      arch/x86/kernel/sysfb.o
  CC      arch/x86/kernel/sysfb_simplefb.o
  CC      arch/x86/kernel/sysfb_efi.o
  CC      arch/x86/kernel/perf_regs.o
  CC      arch/x86/kernel/tracepoint.o
  CC      arch/x86/kernel/umip.o
arch/x86/kernel/umip.o: warning: objtool: fixup_umip_exception()+0x134: can't find jump dest instruction at .text+0x1b6
  CC      arch/x86/kernel/unwind_orc.o
arch/x86/kernel/unwind_orc.o: warning: objtool: __unwind_start()+0x70: return with modified stack frame
  CC      arch/x86/kernel/amd_gart_64.o
arch/x86/kernel/amd_gart_64.o: warning: objtool: gart_iommu_init()+0xbc: can't find jump dest instruction at .init.text+0x22d
  CC      arch/x86/kernel/aperture_64.o
arch/x86/kernel/aperture_64.o: warning: objtool: early_gart_iommu_check()+0x125: can't find jump dest instruction at .init.text+0x4ac
  CC      arch/x86/kernel/pci-calgary_64.o
  CC      arch/x86/kernel/tce_64.o
  CC      arch/x86/kernel/mmconf-fam10h_64.o
  CC      arch/x86/kernel/vsmp_64.o
arch/x86/kernel/vsmp_64.o: warning: objtool: vsmp_init()+0x9e: can't find jump dest instruction at .init.text+0xb0
  AR      arch/x86/kernel/built-in.a
  AS      arch/x86/kernel/head_64.o
  CC      arch/x86/kernel/head64.o

during GIMPLE pass: wrestrict
En la función ‘copy_bootdata’:
en pp_format, en pretty-print.c:1393
  379 | static void __init copy_bootdata(char *real_mode_data)
      |                    ^~~~~~~~~~~~~
Por favor, envíe un informe completo de errores,
con el código preprocesado si es apropiado.
Véase <https://bugs.archlinux.org/> para instrucciones.
make[2]: *** [scripts/Makefile.build:279: arch/x86/kernel/head64.o] Error 1
make[1]: *** [scripts/Makefile.build:489: arch/x86/kernel] Error 2
make: *** [Makefile:1075: arch/x86] Error 2
==> ERROR: Se produjo un fallo en build().
    Cancelando...
`

**Comment by Tk-Glitch** [comment]
After a quick search I suppose you have selected piledriver as µarch? If you did, can you try with bulldozer or native instead?
Else I'll need more information on the exact settings you have selected as well as your CPU.

**Comment by Jordi234** [comment]
Yes, I selected piledriver. I have an AMD A6-5400K, and uses this arquitecture, or not? Is the same selecting piledriver or other options? 
The 5.1 build worked perfectly with piledriver option, and works very well.

**Comment by Tk-Glitch** [comment]
I just want to know if selecting native or bulldozer builds fine for you. There has been regressions in GCC before regarding piledriver so I want to make sure. That code hasn't changed between 5.1 and 5.2 btw.

**Comment by Jordi234** [comment]
Nothing changed selecting bulldozer or native...I see the same error

**Comment by skeevy420** [comment]
It might just be something in 5.2.  I built 5.2 yesterday and none of the Steam games I tried would play (Hitman 2, F1 2017, Dirt Rally).  Rebooted into 5.1 and all was well; using as close to the same configuration between the two kernels as possible.  I'm using westmere.

I was trying to run Hitman 2 under various Vulkan implementations yesterday (and found an AMDGPU vsync bug in the process) so I haven't looked into debugging the kernel at all.  Just rebooted and use a working setup.

Oh, AMDVLK-Pro 19.30 is out.  Been using it for the past 3 days with my RX 580 with really good results on Hitman 2.  That Navi-only comment with its release doesn't apply to us.

**Comment by Tk-Glitch** [comment]
@Jordi234 What about generic (default) then?

**Comment by Jordi234** [comment]
The same, identical error. 
One thing, when the process starts, the terminal write acess denied to pkg folder. I changed the pkg folder's permissions and always returns to locked for all users. Is this normal?

**Comment by Tk-Glitch** [comment]
Makepkg will change the permissions by itself for safety, so that's expected. That being said, I have verified on my end that 5.2 builds fine on westmere, sandy-bridge, skylake as well as zen and zen+, and I have at least one piledriver user confirming he had no issue as well.
If your CPU and/or RAM is overclocked, please try stock clocks to make sure it's not caused by an instability with your settings.
Also, is your system up to date? What GCC version are you using to build the kernel? :frog:

**Comment by Tk-Glitch** [comment]
I think I have found your issue : <https://www.linuxquestions.org/questions/slackware-14/make-linux-4-19-42-error-4175653720/>
Please let us know how it goes.

**Comment by Jordi234** [comment]
Well, works with export LANG=en_US.UTF-8. Thanks.
2 questions: 
I stopped the build process because after a lot of hours not finished....how many time takes the build process? On the 5.1 not takes much time to build the kernel (few hours).
And, what's this option? "Debug preemptible kernel (DEBUG_PREEMPT) [Y/n/?] (NEW)"
I need to select Y or n? I selected Y, seems the default option, but is possible that this option makes the build process slower?
Thanks!

**Comment by Tk-Glitch** [comment]
It takes about 15 minutes on my machine.

Make sure you have set makepkg to use all your threads for compilation : <https://wiki.archlinux.org/index.php/Makepkg#Parallel_compilation> (`MAKEFLAGS="-j$(nproc)"` in `/etc/makepkg.conf`)
Alternatively, you can edit `customization.cfg` next to the kernel's PKGBUILD and set the `_force_all_threads` option to `"true"`, but I'd recommend doing it globally for makepkg to speedup all your package building processes in the future.

For `DEBUG_PREEMPT`, it looks like I omitted it on my end (I have pushed an update that will explicitely disable it), but the difference between enabled and disabled is very small regarding compilation times.

**Comment by Jordi234** [comment]
I added this line to makepkg.conf, and after 2.30 hours the process not finished. I see in task manager 0% of CPU usage, and terminal on this line "CC      net/ipv4/udplite.o", I don't know what happens, I'm a noob, but is impossible to build updates for the kernel with this build time. If is not possible to solve this, I stay with the "default" archlinux kernel.

**Comment by skeevy420** [comment]
My X5687s have similar single thread performance as your A6-5400K (based on CPUBoss) so I timed my system with all the threads available (8C/16T) and then disabled hyperthreading in the BIOS and ran it with just 2 threads to see about how long it should take you to build the kernel.  

Note that I'm compiling on a 24GB ramdisk to minimize read/write times, not using ccache, and not using modprobeddb.

16 threads (8C/16T) "time makepkg -f"
 * hyperthreading enabled
 * -j16 used in makepkg.conf
 * _force_all_threads="true" in customization.cfg
 * schedutil governor
```
real    30m21.596s
user    240m16.342s
sys     24m39.446s
```

2 threads (2C/2T) "time makepkg -f"
 * hyperthreading disabled
 * -j2 used in makepkg.conf
 * _force_all_threads="false" in customization.cfg
 * schedutil governor
```
real    109m29.206s
user    175m34.305s
sys     18m8.358s
```
Based on that testing, you should check to see if you aren't being thermal throttled during the compile.  That's a common issue with APUs and would explain it taking over 2 and a half hours.  A minute and a half from both times is due to my insanely high XZ compression settings.

As far as your error, are you deleting your makepkg build directory in-between builds?  If I intentionally cancel out a build (crtl+c) I often have failures on the next build if I don't wipe "/tmp/makepkg/linux*".  "/tmp/makepkg" is the custom directory I use to build my packages with /tmp on ram.

**Comment by Jordi234** [comment]
Well, finally I can build the kernel :S
When you said thermal throttled, AMD Cool&Quiet it has come to my mind. I disabled it and configured MAKEFLAGS="-j$(nproc)+1 and other things, except schedutil governor, if I put shedutil the build fails and shows error. I used ccache this time (is a bad idea?). I saw much speed writing lines on the terminal, and the process finished with:
`real	124m39.658s
user	197m48.431s
sys	32m16.217s
`
Is better but not perfect. I will try other configs (j3 and j16) on future builds, or building wine for example.
Thanks for the help!

**Comment by skeevy420** [comment]
Don't use -j16.  My system has two quad core CPUs in it and that tells the build system to use 1 thread for each of my available hyperthreads.  -j16 on a dual core would be like trying to build 8 kernels at once...16 active threads fighting over two cores will slow your build down.

-j2 or -j3 are all you should need to use.  The unofficial rules are number of threads or number of threads + one.  Number of threads + one can be faster since there's always a job queued up and ready when one finishes, but recent scheduler advancements have made that less necessary.  Still, if I was on a dual core system, it would be one of the first things I tested.

schedutil is geared towards Intel CPUs.  Odd that a frequency governor caused the build to fail.

**Comment by Tk-Glitch** [comment]
@Jordi234 On such a little CPU as yours with only 2 threads, you don't want to go past `-j3`, as skeevy420 noted above. Using CCACHE will slow down the initial build times a bit, but the subsequent builds will be *much* faster. That schedutil governor issue you got is weird though.

**Comment by Jordi234** [comment]
Thanks to all !!!
