### ISSUE TITLE
[wine-tkg-git] DXVK and D9VK (possibly all vulkan) games with lower than desktop resolution behave weirdly

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Tk-Glitch/PKGBUILDS#243]
Something like this: https://github.com/Joshua-Ashton/d9vk/issues/193
But in my case, it behaves slightly differently. Picture of SpellForce 2 (running at 2560x1440 on 3840x2160 desktop; proton fullscreen hack active):

![Screenshot_20190711_154651](https://user-images.githubusercontent.com/11160972/61056483-b7f24880-a3f3-11e9-8f82-b9386d094f3d.jpg)

Bottom and right parts of picture are cut. How it should look like (at 3840x2160, because I can't take screenshot at lower resolution due to this bug):

![Screenshot_20190711_160831](https://user-images.githubusercontent.com/11160972/61057836-5c758a00-a3f6-11e9-9e66-7b683ccaad53.jpg)

And it seems to get stuck at this frame, because no matter what I do, I can't see mouse movement or menu highlighting. Something similar happens to Stronghold HD over dgVodoo2 - it gets stuck at loading screen. In both cases, alt tabing out and back in causes game to become black rectangle but in top left corner of the screen with desktop visible in the rest. Running SpellForce 2 at desktop resolution fixes the issue and game is playable. Virtual desktop also works (but game can run at higher than virtual desktop resoltion and make alt+tab useless as it is always on top of everything -- not sure if bug).

I am on AMD RADV POLARIS10 (LLVM 9.0.0), built from git 2 days before this was posted.

**Comment by skeevy420** [comment]
If you have it enabled, disable any vsync.  Myself and others have all experienced issues that are ultimately caused from Vsync and it's independent of RADV, AMDVLK, or AMDVLK-Pro.  AMDVLK & Pro seem to be effected more by it.

Setting Vsync to never in the system settings and disabling it in-game fixes Vsync issues in games on my Plasma desktop so you don't necessarily have to mess with xorg.conf or amdPalSettings.cfg (for configuring AMDVLK & Pro).

Vsync being enabled may or may not be related to your issues, but since you didn't mention it I though it would be worth mentioning.

**Comment by neVERberleRfellerER** [comment]
Disabling vsync (both in Plasma settings and in game) does not help.
I have noticed that alt tab sometimes crashes these bugged games and the rectangle is kept alive by winedbg. It is necessary to kill winedbg from another virtual terminal, because screen is locked with black rectangle being always on top.

**Comment by skeevy420** [comment]
Damn, at least buggy vsync is ruled out.  

I'll try running some of my games at less than 1080p (my desktop and gaming resolution) and see if I can't trigger it to help you further.  I have to mow my yard and do some other things so it'll be awhile before I get a chance.

**Comment by neVERberleRfellerER** [comment]
> have you tried AMDVLK or AMDVLK-Pro?

Only OSS AMDVLK (2019.Q3.1) and it's exactly the same.

**Comment by skeevy420** [comment]
So far I've tried Hitman 2, Oblivion, & Skyrim, all with multiple Vulkan implementations, and none of them behaved like that when setting the game's resolution lower than my desktop's 1080p.  They played as expected.  Using Mesa 19.1, LLVM 8.0.0, Kernel 5.2, Manjaro, RX 580 4GB.

I don't have the two games you have.  Know of any other games that do this?  
Does it do this with non-git builds?

**Comment by neVERberleRfellerER** [comment]
> Does it do this with non-git builds?

It happens also with non-git version of everything except wine-tkg-git, because I am not going to let resolution change to wreck my desktop layout.

Okay, so I am probably crazy, but it seems that when I run SpellForce 2 or Stronghold HD over dgVodoo2 in lower than desktop resolution, it breaks something and  when I run any Mass Effect 2 in less than native resoltion, it gets rendered incorrectly. When I run anything (tested with Spellforce 2, Mass Effect 2) in desktop resolution then Mass Effect 2 get rendered correctly even when in less than native resolution. Multiple round sof testing confirm this. dgVodoo2 might be proken by something totally unrelated which needs further investigation.

Anyway, this very probably isn't wine (`wineserver -k` would fix this, right?) bug so I'll close this until some kind of future evidence proves me wrong.

**Comment by skeevy420** [comment]
Don't think you're that crazy.  AMDGPU has a crazy finicky vsync bug that can cause other weird bugs down the line to trigger.  It's been my biggest annoyance lately.

With Hitman 2, vsync causes mouse looking to stutter and it doesn't matter if it's RADV, AMDVLK, or AMDVLK-Pro.  With a PS4 controller it'll act like the right stick gets stuck.  Turn vsync off and both are fixed.

With AMDVLK or Pro and Hitman 2, vsync causes issues if the shadow settings are changed to ultra while in-game, going back to High doesn't fix it, but going to Medium or turning off vsync does.  That does not happen with RADV.

Both are vsync issues but one triggers AMDVLK versions and the other triggers all Vulkan implementations.

Thank goodness kernel 5.2 seems to have fixed both of those issues for me.

Just saying, don't think you're crazy because some of these issues are weird, odd, and a pain to track down.
