### ISSUE TITLE
Mesa-revert script (idea)

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#244]
Some users of arch linux testing mesa-git and mesa-aco, but then this packages on AUR abandoned and absolete.

Please, make script for reverting mesa packages to official repos (arch/manjaro)

I always testing newest mesa with fresh DXVK, and reverting mesa to normal state is boring and dangerous.

**Comment by Tk-Glitch** [comment]
I have partially addressed the issue with the new https://github.com/Tk-Glitch/PKGBUILDS/tree/master/mesa-git package. It's closer to stock Arch packages and should be a safe replacement for "experimentation purposes" or simply living on the bleeding edge, while not preventing safely going back to official repo packages if needed.
What do you think?

**Comment by t14462** [comment]
I think, with ACO fresh Mesa much stable. But, for safe little manually verification needed.

I cant build Mesa-git from AUR, because of it LLVM-hell dependencies. Mesa-git in unofficial repo compiles from git by timer, without any verification (sometimes it breaks Qt and KDE Plasma)

So yours variant smarter than others.
====

Now I'm using Mesa-ACO from AUR - this variant does not contain LLVM-hell

**Comment by skeevy420** [comment]
I also came to mention something about the LLVM dependency hell with the full git version which, for me, was solved by installing everything at once -- llvm-git llvm-tools-git lib32-llvm-git lib32-llvm-tools-git.  It needs to be installed with: 

`**makeopts="--nocheck -f"** pacaur -Sya llvm-git llvm-libs-git lib32-llvm-git lib32-llvm-libs-git`

"pacaur" can be swapped with the usual makepkg/pacman combo, but, basically, makepkg needs --nocheck passed because the LLVM tests are failing (at least they were last night).  While I passed -f to force it, I'm not sure if that's needed or not.  

I keep -f aliased to force package rebuilds because makepkg isn't smart enough to realize that GCC/libc/QT/KDE/etc updated and therefore I need to rebuild my AUR packages and not have it tell me, "oh, you already built this version, why don't I reinstall that for you".

It, llvm-git, also has issues with KDevelop (current Manjaro stable version depends on clang 8 and llvm-git provides clang 10) and it was a serious PITA to deal with removing KDevelop due to KDE Meta package dependency hell.  Just a little FYI for the KDE users among us.

There's also a slight issue with the current way to install "libglvnd-glesv2" before doing a mesa-git build -- it and Mesa (stable/Manjaro repository version) have the same files so I had to force install it with:

`pacman -U --overwrite /usr/lib/pkgconfig/egl.pc --overwrite /usr/lib/pkgconfig/glesv2.pc ~/Projects/makepkg/packages/libglvnd-glesv2-1.1.1-2-x86_64.pkg.tar.xz `

After that everything went smoothly and I had a fully working Mesa 19.2 build.

My two cents:

A "_use_libglvnd-glesv2" option that can track the overwrite, if necessary, and revert it on a mesa-git failure would be really handy for those who aren't power users....though it may not be necessary when 19.2 is released and the repositories get updated to reflect the change.

An LLVM build script with a "_no_tests" option would also help the non-power users among us.
