### ISSUE TITLE
league of legends still crashes after selecting champion with "lol fixes on"

### ISSUE THREAD

**Issue by barfin** [Tk-Glitch/PKGBUILDS#254]
using wine-tkg-4.12.1.r18.g5d7a86d0

**Comment by Tk-Glitch** [comment]
Unless there's been an update that I'm unaware of breaking it even more (and maybe for good :frog: ), are you disabling vdso32 (as root : `echo 0 > /proc/sys/abi/vsyscall32`) in your session before starting the game? The patch won't work otherwise.
An alternative way is to build wine without 64-bit support and use the resulting 32-bit only wine build to play the game.

**Comment by barfin** [comment]
> Unless there's been an update that I'm unaware of breaking it even more (and maybe for good frog ), are you disabling vdso32 (as root : `echo 0 > /proc/sys/abi/vsyscall32`) in your session before starting the game? The patch won't work otherwise.
> An alternative way is to build wine without 64-bit support and use the resulting 32-bit only wine build to play the game.

yeah it worked by disabling that but i remember that i had disabled that
does it somehow it goes back 1?

**Comment by Tk-Glitch** [comment]
Yes, each time you reboot.

**Comment by barfin** [comment]
> Yes, each time you reboot.

it there a way to permanently disable it?

**Comment by varris1** [comment]
@barfin You can try this:
`
echo "abi.vsyscall32 = 0" > /etc/sysctl.d/99-vsyscall.conf
sysctl --system
`

**Comment by barfin** [comment]
> @barfin You can try this:
> 
> `echo "abi.vsyscall32 = 0" > /etc/sysctl.d/99-vsyscall.conf`
> `sysctl --system`

nice
