### ISSUE TITLE
How to use kernel 52 on manjaro?

### ISSUE THREAD

**Issue by Jordi234** [Tk-Glitch/PKGBUILDS#258]
Hi again.
Recently I decided to install Manjaro on my computer, and I wish to continue using your kernel. I compiled correctly the kernel, but now I have a problem with Nvidia drivers. On Arch simply installing nvidia-dkms package solves the issue, but on Manjaro don't appears this nvidia-dkms package. When I try to boot the kernel, nvidia and nvidia-drm modules error appears.
What is the way to use this on Manjaro?
Thank you!

**Comment by skeevy420** [comment]
Sounds like an Nvidia issue; not necessarily a kernel issue.  On Manjaro, what I use too with the 52 kernel oddly enough, with an AMD GPU it's usually as simple as fill out the config or answer the questions properly, run "makepkg -sif", and reboot.  The only time it doesn't work like that is updating AUR kernels to higher versions.
  
I'd check that MHWD isn't interfering with anything as well as uninstall any Manjaro provided Nvidia drivers.  It has been the cause of a few driver issues I've dealt with over the years due to using AUR packages and being an AMDGPU early adopter.

Once you start doing things in a more power user manner, mhwd and other various Manjaro helpers tend to start getting in your way.

Oh, and on kernel version updates, like linux51-tkg to linux52-tkg, I have to manually update the bootloader on Manjaro.  Once I do that it works just fine until the next version update.  I'm really lazy so I use "grub-customizer" from the AUR and I right click on the kernel I just updated to, select edit, copy the boot script, and replace the boot script in the default Manjaro Linux entry.

If you installed the drivers and an updated kernel version both at once, that might be your problem and a quick enough of a workaround is to just select the updated kernel under "Advanced Options For Manjaro Linux" in the Grub menu...that sub-menu is where Manjaro installs all my TKG & AUR kernels at.

I've had to do some form of Grub tweaking with a lot of custom kernels on Manjaro over the years so that really isn't an issue with TKG packages; more a Manjaro quirk than anything else.

**Comment by Jordi234** [comment]
OMG...sounds really tedious.
Sorry, I don't understand what I need to do. Is necessary to install nvidia-tkg packages from this site and the Linux52 Kernel? I builded nvidia-tkg packages and when I go to install it, are in conflict with the drivers installed. Is secure erase the official Nvidia drivers from manjaro and install the tkg?
A detail, I builded with modprobed-db directly this time, with the official kernel. On Arch I builded with modprobed on tkg kernel, builded without modprobed-db.

**Comment by skeevy420** [comment]
Not really as tedious as it sounds, takes longer to open the app and save it than anything else since it's just copy/pasting text from one entry to another.

That'll happen when you install the Nvidia drivers from here (or anywhere else) over the Manjaro ones; it's supposed to do that.

Just reinstall nvidia-all and let it remove the system provided packages when prompted.  Let pacman do it's thing and just say yes when it asks if you want to remove the Manjaro provided drivers.  

I haven't bothered with modprobe-db.  Just really haven't taken the time to do it.  If you didn't use it on this build or on Manjaro yet, then it isn't a factor to consider here.

**Comment by Jordi234** [comment]
Well, I builded a regular version, installed and made sudo mkinitcpio -P. The error dissapeared, and now is working with official kernel only, I have another error:
[code]
Failed to mount /boot/efi
[/code]
On systemctl status boot-efi.mount:
[code]
boot-efi.mount - /boot/efi
Loaded: loaded (/etc/fstab: generated)
Active: failed (Result: exit-code)
Where: /boot/efi
What: /dev/disk/by-uuid/xxx-xxx
Docs: man:fstab(5) man:systemd-fstab-generator(8)
Mounting /boot/efi
mount: /boot/efi: incorrect filesystem
(...)
[/code]

**Comment by skeevy420** [comment]
I've never had an EFI system so I'm not really sure on that.  Based on a quick search, similar errors tend to come up if the HOOKS line of mkinitcpio.conf isn't correct; some module failed to compile or needs to be added to the initramfs; and other such issues when updating kernels and drivers.  

Quickest and easiest fix seems to be to reboot into a live environment, mount all your drives, chroot into your install, remove all the TKG kernels and drivers while simultaneously reinstalling the Manjaro kernel and drivers as well as ensuring that mkinitcpio.conf is setup correctly before doing that.  

mkinitcpio shouldn't have been necessary since a pacman hook is triggered for that when kernels and modules are installed.  While YMMV, I haven't needed to run it a single time on my current Manjaro install from February until now since pacman has always triggered it when it should have.

**Comment by Tk-Glitch** [comment]
@Jordi234 Modprobed-db seems to have made an incomplete kernel. Rebuilding without using it should fix your issue. I'll disable the prompt about modprobed-db by default, I'm getting tired of all the issues with it.

**Comment by Jordi234** [comment]
I can enter to the system with the official Manjaro kernel. Is not possible to do this with the installed system?
I don't understand this:  ensuring that mkinitcpio.conf is setup correctly before doing that.
Where i can find correct setup? Sorry but I never made this configurations on Linux, is the first time that I use a custom kernel.

**Comment by skeevy420** [comment]
I don't know if this is an unfounded fear or not, but I've always been worried that I'd be on 4.19 for a while, update to 5.1 or 5.2 or whatever, and then modprobe-db wouldn't catch or know to build some new module that I may need with the new kernel while me simultaneously forgetting I was using modprobe-db and that I should disable it upon updating kernel versions.

Is that something that can happen with modprobe-db?

Off topic, I have some updated nativeopt.d*vkpatch patches if you're interested.  They're not 100% stock to what you'd use so I didn't want to submit 'em in a pull request.

**Comment by Jordi234** [comment]
Rebuiling.
I thought in modprobed-db from the start, I will try again on the next update, on the tkg kernel, if I can use it. On Arch I used modprobed-db without problems, but made the config on tkg kernel.
@skeevy420 the patches you mentioned offers a significant performance jump? I'm interested to learn about this type of things, and no problem to try it.

**Comment by skeevy420** [comment]
Don't know, I only updated the patches and know that they compile. Nothing more than march/mtune native and my other makepkg.conf defaults.  I've yet to compile Proton and inject them in.  Both files are identical so just replace both with this and remove the "b" from the end of the file names.

```
From d5f571da7ac5dd376b8c92c5382696ec156ef738 Mon Sep 17 00:00:00 2001
From: Tk-Glitch <ti3nou@gmail.com>
Date: Tue, 9 Oct 2018 22:37:20 +0200
Subject: march native


diff --git a/build-win32.txt b/build-win32.txt
index 0865fc5e..2f25ca0b 100644
--- a/build-win32.txt
+++ b/build-win32.txt
@@ -5,8 +5,8 @@ ar = 'i686-w64-mingw32-ar'
 strip = 'i686-w64-mingw32-strip'
 
 [properties]
-c_args=['-msse', '-msse2']
-cpp_args=['-msse', '-msse2']
+c_args=['-msse', '-msse2', '-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
+cpp_args=['-msse', '-msse2', '-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
 c_link_args = ['-static', '-static-libgcc']
 cpp_link_args = ['-static', '-static-libgcc', '-static-libstdc++', '-Wl,--add-stdcall-alias,--enable-stdcall-fixup']
 needs_exe_wrapper = true
 
diff --git a/build-win64.txt b/build-win64.txt
index 2a7fbee3..3c56909a 100644
--- a/build-win64.txt
+++ b/build-win64.txt
@@ -5,6 +5,8 @@ ar = 'x86_64-w64-mingw32-ar'
 strip = 'x86_64-w64-mingw32-strip'
 
 [properties]
+c_args=['-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
+cpp_args=['-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
 c_link_args = ['-static', '-static-libgcc']
 cpp_link_args = ['-static', '-static-libgcc', '-static-libstdc++']
 needs_exe_wrapper = true
 
diff --git a/build-wine32.txt b/build-wine32.txt
index 4b830f7e..6dde5465 100644
--- a/build-wine32.txt
+++ b/build-wine32.txt
@@ -7,8 +7,8 @@ strip = 'strip'
 [properties]
 needs_exe_wrapper = true
 
-c_args=['-m32', '-msse', '-msse2', '-fvisibility=hidden']
-cpp_args=['-m32', '--no-gnu-unique', '-msse', '-msse2', '-fvisibility=hidden', '-fvisibility-inlines-hidden']
+c_args=['-m32', '-msse', '-msse2', '-fvisibility=hidden' '-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
+cpp_args=['-m32', '--no-gnu-unique', '-msse', '-msse2', '-fvisibility=hidden', '-fvisibility-inlines-hidden' '-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
 cpp_link_args=['-m32', '-mwindows']
 
 [host_machine]
 
diff --git a/build-wine64.txt b/build-wine64.txt
index 09b1c38b..fd09a3fd 100644
--- a/build-wine64.txt
+++ b/build-wine64.txt
@@ -7,8 +7,8 @@ strip = 'strip'
 [properties]
 needs_exe_wrapper = true
 
-c_args=['-m64', '-fvisibility=hidden']
-cpp_args=['-m64', '--no-gnu-unique', '-fvisibility=hidden', '-fvisibility-inlines-hidden']
+c_args=['-m64', '-fvisibility=hidden' '-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
+cpp_args=['-m64', '--no-gnu-unique', '-fvisibility=hidden', '-fvisibility-inlines-hidden' '-march=native', '-mtune=native', '-O2', '-ftree-vectorize', '-ftree-slp-vectorize', '-pipe']
 cpp_link_args=['-m64', '-mwindows']
 
 [host_machine]


 

```

**Comment by skeevy420** [comment]
PKGBUILDS/dxvk-tools/DXVKBUILD/patches/nativeopt.dxvkpatchb
&
PKGBUILDS/dxvk-tools/D9VKBUILD/patches/nativeopt.d9vkpatchb

The same thing above goes in each of those since the receive identical patches and changes, remove the "b" from the end of the file names else the script won't use them, follow the standard dxvk-tools instructions ( "./upd9vk build && ./upd9vk proton-tkg && ./updxvk build && ./updxvk proton-tkg" from the dxvk-tools directory), & then build Proton with dxvk/d9vk set to use prebuilt.

I may or may not have a few minutes to actually test this on fresh builds after posting.  Busy morning, you know.

**Comment by Jordi234** [comment]
@skeevy420 Ok, thank you. I will try this later.
Well, kernel builded and working, but without network connection. I can't access to network. I don't know what commands I need to type to find the problem.
A detail, I found a simple ¿benchmark?, is this:
time $(i=0; while (( i < 9999999 )); do (( i ++ )); done)
I had the same result with tkg kernel and manjaro kernel, 34 seconds. Is strange because with Arch i feel a great performance change with tkg kernel....is this benchmark useful?

**Comment by Tk-Glitch** [comment]
Sounds like the manjaro module striked again. You'll want to install https://aur.archlinux.org/packages/r8168-dkms/ instead of the manjaro r8168 module.

**Comment by Tk-Glitch** [comment]
Regarding your performance testing question, synthetic benchmarks will usually fail to "reveal" the gains. We're mostly talking about latency/interactivity gains here (that's why desktop feels that much smoother), and not throughput (for which the stock kernel is good at already). Using games as benchmarks should give better results on that front :)

**Comment by ronoverdrive** [comment]
I had the same issue with my realtek network chipset drivers when I tried Manjaro. Installing the dkms driver from the AUR like Tk said should fix it. Honestly this is just one of the many problems I've seen Manjaro has because of their effort to turn Arch into something more like Ubuntu or Mint breaks things with the AUR and some drivers.

@skeevy420 try doing this: https://wiki.archlinux.org/index.php/Gamepad#Joystick_not_recognized_by_all_programs it fixed many of my game pad issues.

**Comment by skeevy420** [comment]
@ronoverdrive I'll give that a shot.  Thanks for the tip.  This issue has only occurred with stock & tkg Proton 4.11 and Hitman 2.  Earlier Proton builds or from Valve work just fine.

**Comment by Tk-Glitch** [comment]
@skeevy420 Regarding your "'optimizations", please refrain from posting about it in unrelated issues as that only makes things confusing for no reason. Thanks.
There's a place for that already, and having them all centralized would be the best : https://github.com/Tk-Glitch/PKGBUILDS/issues/204
Regarding DXVK, most compiler flags have been tested already. Anything else than `-march=native` basically either hurts performance, creates bugs or has no effect. `-O3` was also slower than `-O2`. So not worth it at all.

Back on topic.

**Comment by skeevy420** [comment]
No problem, removed it.

**Comment by Tk-Glitch** [comment]
Other people answered you already so "too late" I guess :frog: This issue is a total mess.
@Jordi234 Please let me know how if https://aur.archlinux.org/packages/r8168-dkms/ fixed your network problem :D

**Comment by Jordi234** [comment]
Well, I decided go out from manjaro. I returned to Arch.
I was looking for alternative to Arch, basically, Arch forums are not the best place for noobs, I feel something like hate to people that starting with ArchLinux system. But, after a lot of tries (EndeavourOs, RebornOs, Lubuntu, LMDE, Fedora, etc) I can't found a better option to stay. ArchLinux system simply FLY on my computer, all is very very fast and stable, except a little problem (again) on certain moments  with the network. On all the distros I had problems only start using it. Manjaro was not a exception...the system works very slow, for example opening firefox or browsing webs, and the builds of this kernel take 4 hours....I opened a question here saying this "problem", and finally I got to complete build on 2 hours or less...I don't understand nothing.
For this, I decided reinstall Arch and I thing is the best option, and probably the best distro at the moment (my opinion).
I apologize for wasting your time, thank you again for your great explanations and help.

**Comment by Tk-Glitch** [comment]
Learning is never a waste of time. For your compilation times, makes sure to set makepkg to use all your cores (that's also valid for "pure Arch") : https://wiki.archlinux.org/index.php/Makepkg#Parallel_compilation

**Comment by Jordi234** [comment]
Yes, all is configured. I now building and (re)trying on Arch.
I used Antergos for a long long time, I never had problems with this distro, was great always, but now is discontinued :(
Seems RebornOs is very close to Antergos, but I installed it and it was impossible to boot when I made the installation. Another option, Endeavour, the same. Pure Arch works perfect from first try.

**Comment by skeevy420** [comment]
The thing to remember with Manjaro is its kernels contain AUR modules by default.  When you switch to non-stock kernels you have to make sure you have all the corresponding AUR modules installed that you were using with the stock kernels.  Manjaro's Linux51, for an example, has 11 different AUR modules not including proprietary graphics modules.  I had to install the exact same packages others here have suggested...only my system isn't EFI based so not having those modules didn't leave me with a non-booting system.  Yay old crap.

An added thing to remember, Arch, Manjaro, Endeavour, etc, is to make sure all the dkms modules compile when doing kernel updates.  ZFS isn't compiling with 5.3 for me right now but, even with the module compile fail, the kernel will still be installed and will be set to be booted from.  That's why I always have multiple working backup kernels installed; LTS and mainline right now.  I learned that one the hard way after switching over to ZFS.

I also have to +100 @Tk-Glitch 's learning is never a waste of time comment. I try to learn something almost every day which is why I like projects like this.  Keeping up with the latest and greatest keep me on my toes in regards to gaming tech on Linux.

Manjaro does have it's quirks that have to be learned, but once learned it does make a nice alternative to Arch.  I've been bitten way too many times by "_Arch stable left my system not booting after an update even after check for issues beforehand_" on both Antergos and Arch that the extra layer of testing Manjaro provides makes it worth learning and mitigating their "_helpful_" tools and methods that are "_just terrific_" for power users.

**Comment by Jordi234** [comment]
Well, initially, I cancelled the build because after 3 hours not finished. Then, I searched more info and I made some changes on makepkg.conf, exactly this:

CFLAGS="-march=native -O2 -pipe -fstack-protector-strong -fno-plt"
CXXFLAGS="${CFLAGS}"
MAKEFLAGS="-j$(nproc)+1"
PKGEXT='.pkg.tar'

And maybe other that I can't remember. I started again the compilation and finished with (surprise xD):
real    76m30.146s
user    66m59.293s
sys     16m37.028s

Installed and working perfectly, and another good thing, I made the time test that I mentioned before, and now with tkg kernel changed the result from 34 secons with official kernel to 32 secons, is a little bit difference but is really good.
On next builds I will try again modprobed-db, it works perfect for me before my stupid try to go to another distro :S.

Thanks to all!

**Comment by skeevy420** [comment]
On the next pacman release we'll have zstd support.  Just a tip to remember for future use because, using linux 5.2 as a benchmark, it's almost 50% faster than XZ on my system with slightly less compression.  It compresses the kernel one minute faster with only 8 more mb (1:15 vs 2:24; 101.7mb vs 108.2mb)

COMPRESSXZ=(xz -c -z -e -9 -T0 -) vs COMPRESSZST=(zstd -c -z -q -T0 19 -)

This topic should likely be closed now since @Jordi234 went back to Arch and, therefore, no longer has this Manjaro issue.
