### ISSUE TITLE
A little detail to build proton-tkg

### ISSUE THREAD

**Issue by Jordi234** [Tk-Glitch/PKGBUILDS#264]
I would like to comment here a little detail that happened on my build try with proton-tkg. 
When I executed the installation script all worked perfectly just before Gandalf message. Then, an error appeared, exactly "libspiro.so.1: no such file". I searched and I installed manually "libspiro" package with "pacman -S". Then, the build finished without more problems.
I would like to write here this half-issue because I see very automated processes, and I think maybe useful, because seems that dependency not appears (or I can't found) on any info.
Proton-tkg works perfect for me.
Thanks!

**Comment by skeevy420** [comment]
Due to @Jordi234's head's up, I checked Manjaro and its version of "libspiro" is too old and doesn't contain that file nor is it available in the AUR to use a "git" version as a temporary stop-gap.  Manjaro users are up that creek without a paddle until the next Manjaro update unless they build it from Arch's source package.
