### ISSUE TITLE
bunch of userpatch suggestions

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#298]
Hello,
I'm using these mostly non-invasive changes, which can have quite a big benefit, and perhaps you find them suitable for a broader audience.

For wine-tkg:
Reverting this old commit ( https://github.com/wine-mirror/wine/commit/c6b6935bb433dbbd30f5ba122a7c45ad3a2d6eed ) due to this bug:
https://bugs.winehq.org/show_bug.cgi?id=47752
It bummed me out for months and basically ruined usage of the new amdgpu display stack. :(
Have not received feedback yet by the wine devs, but imho it's a must.

For linux-tkg:
This patch to allow dynamic video memory clocking with amdgpu and 75Hz display:
https://cgit.freedesktop.org/~agd5f/linux/commit/?h=amd-staging-drm-next&id=b396b001487db18ac84d8d773d0234ac6b376dea
Works without bad side effects for me with 1440p 75Hz. Might get included in linux 5.5.
Not to be confused with the userpatch that enforces full VRAM clock to workaround the flicker e.g. with multi-monitor at the cost of higher power consumption.

This fix which helps against stuttering with xf86-video-amdgpu:
https://cgit.freedesktop.org/~agd5f/linux/commit/?h=drm-next&id=e16e37efb4c9eb7bcb9dab756c975040c5257e98
This e.g. fixes stuttering when scrolling with the mouse wheel on websites and the cursor triggers some text pop ups etc. Will be included in linux 5.4.

For Mesa:
It conflicts with the userpatches for Josh's experimental extensions, but I suppose DXVK doesn't use them (haven't checked that actually) and thus shadows look incorrect with radv & dxvk:
https://bugs.freedesktop.org/show_bug.cgi?id=109599
Samuel posted a patch which equals the native D3D11 look:
https://bugs.freedesktop.org/attachment.cgi?id=144120
I haven't observed issues with it applied yet in native Vulkan games.

**Comment by Tk-Glitch** [comment]
Thanks for sharing these and your feedback about them with us! I'll definitely consider adding them.

Josh's extensions are only used by D9VK as of yet afaik, and there's a fallback path available in case they are missing.

On another note, the userpatch situation got me thinking.. I've had various requests about merging patches and to be honest, merging everything would likely end up being too much maintenance work for me alone. Due to the number of requests to process (most of them being made outside of github, to make things *oh so easy for me*) there can be quite a bit of a delay between the time of the request and its potential actual availability to you, and some of them that would be interesting but are a bit too invasive are put aside.
Would a repository dedicated to userpatches sound like a plan to you?

**Comment by clapbr** [comment]
FWIW I can vouch for those two suggested kernel patches, specially the first one is at least as important as the currently included fix. A userpatch repo is a great idea.

**Comment by skeevy420** [comment]
Just came to +1 that Wine revert suggestion and saw that it was added an hour ago. :grinning: 

That + disabling vsync really, really helps Hitman 2.

Should add that I tested the xf86-video-amdgpu cursor async update at the same time.

**Comment by aufkrawall** [comment]
> Just came to +1 that Wine revert suggestion and saw that it was added an hour ago. grinning
> 
> That + disabling vsync really, really helps Hitman 2.

Nice. Also vsync should work without issues with that commit reverted, I don't notice a difference vs. Windows anymore in various games (whilst it was often terrible before).

Regarding userpatch repository: Sounds like a great idea to make useful fixes more known and accessible. Though I'm not the guy to fiddle with Git commits. :)

**Comment by skeevy420** [comment]
@aufkrawall 
I was just looking at the patches for Josh's VK extensions and that shadow patch and the included depth bias patch only needs line 28 changed from

`+	unsigned bias = fui(d->depth_bias.bias * scale);`
to
`+	unsigned bias = fui(d->depth_bias.bias);`
for Josh's patches to contain that shadow "fix" from the Mesa mailing list.

I am curious if you've tested how shadows look with just Josh's patches since they both change the offending line that caused the issues in your screenshots. 

I'm compiling LLVM right now with Mesa-ACO after that so I thought I'd take a look at those and they were a lot simpler to merge than I expected so I'll compile it with that change.  Gonna test out HM2 with the patches merged (eventually today...I has job :crying_cat_face:)

**Comment by aufkrawall** [comment]
There is now a fix for the Wine input issue in both Wine and Proton:
https://github.com/wine-mirror/wine/commit/cb703739e5c138e3beffab321b84edb129156000
It doesn't completely turn off XResetScreenSaver calls, but it seems to be enough to make games run fine in general.

@skeevy420 I haven't yet checked.

**Comment by skeevy420** [comment]
Cool.  Just started building Proton so that's good news.

I had to rebuild it all because I've been experiencing some odd graphical issues when aiming in Hitman 2 when using a combination of LLVM10, Mesa 19.3 (regular and ACO), & RADV.  Reverted to LLVM9 from the release branch, just finished building that and ACO, and moving on to DXVK+Proton and hopefully that'll fix it.

**Comment by BrosephJ** [comment]
How about the patch to re-enable "Bulk Moves" functionality for amdgpu?

https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Re-Enable-Bulk-Moves

**Comment by telans** [comment]
If [this](https://lists.freedesktop.org/archives/amd-gfx/2019-September/039973.html) is all that's needed, then remove the `.txt` and put the below patch next to the PKGBUILD

[amd_bulkmove.mypatch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3628098/amd_bulkmove.mypatch.txt)

**Comment by skeevy420** [comment]
@telans 

Didn't use your patch specifically, but can confirm the one linked in the OP works well with 5.2.

**Comment by aufkrawall** [comment]
"Allow cursor async updates for framebuffer swaps" has landed in linux 5.3.2.

**Comment by skeevy420** [comment]
@aufkrawall  Thanks for the heads up.  Figured I'd post the current collection of patches I'm using with 5.3.  

Includes the AMDGPU bulk moves patch from 5.5, the ZSTD initramfs patch, & the updated schedutil patch for 5.5 that I saw on Phoronix this morning and I'm currently compiling and haven't even actually used yet.

**Comment by aufkrawall** [comment]
The 75Hz flicker fix has landed in stable kernel.
Btw: Thanks for community-patches feature!

This LFC fix should be interesting for owners of a capable display:
https://cgit.freedesktop.org/~agd5f/linux/commit/?h=drm-next-5.5-wip&id=109b3e3e13507ad0908ff00bc7eb759ed41b88be

**Comment by howaboutsynergy** [comment]
> Figured I'd post the current collection of patches I'm using with 5.3.

been using these two:
> the ZSTD initramfs patch, & the updated schedutil patch for 5.5 that I saw on Phoronix. 

but got a [hang](https://gist.github.com/howaboutsynergy/a18891c58fca76efe954880675e9dd9a#file-crash-log-L32) with 5.3.5 stable, though it may be happening for other reasons!

**Comment by aufkrawall** [comment]
I suppose no need to keep this open. :)
