### ISSUE TITLE
linux-tkg: _default_cpu_gov="performance" + _disable_acpi_cpufreq="true" results in intel_pstate

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#306]
Hello,
when compiling the kernel with that configuration, cpupower frequency-info shows intel_pstate is in use.
Would it be possible to make that config result in no governor being used at all? Else I'd have to add intel_pstate=disable to kernel loading parameters to achieve this.

**Comment by aufkrawall** [comment]
Should have mentioned that the customization.cfg states
 > Enforcing an option will disable intel_pstate altogether!

I suppose now this ticket makes more sense. :)

**Comment by Tk-Glitch** [comment]
After more digging, it looks like we'd need to nuke the cpu_freq driver, but doing so requires disabling a truckload of other kernel functions and at that stage I simply can't see the point anymore. It could also break compat with various stuff. That being said, intel_pstate is not supposed to work on anything non-intel, and even then it requires a Sandy Bridge as bare minimum. I think it's more likely cpupower going south due to acpi_cpufreq not being there, and intel_pstate driver isn't effectively used. Do you see frequency scaling happening with that config? The intel_state driver only has performance and powersave governors, and both are scaling.

**Comment by aufkrawall** [comment]
Yep, intel_pstate is unaffected and clocks down to reported 800MHz with powersave (which btw. runs like garbage on my 6700k).
Well, then it seems we gotta stick to a boot command if we can't stand any governor active. No biggie. :)

**Comment by Tk-Glitch** [comment]
My bad, I was convinced you had a Ryzen. You'd want to put intel_pstate in passive mode and use performance gov I guess. That acts as a passthrough for the (non-scaling) acpi_cpufreq performance governor.

**Comment by aufkrawall** [comment]
Thank you so far!
I suppose I'll simply stick to blacklisting acpi_cpufreq and setting intel_pstate=disable . That way cpupower complains that there is no governor available, which is exactly what I want on my desktop system. :)
As a side note: intel_pstate powersave seems to work much better on my Gemini Lake SoC than on my 6700k.
