### ISSUE TITLE
Just black screen in fullscreen after staging commit

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#328]
Hi there,
starting with staging commit 649c35ff92b4fd86b0ecf5d84d80b595a7c919d9, I only get a black screen + process hang when starting programs with at least DXVK in fullscreen:
[wine.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3662133/wine.log)
Havn't found anything on the wine tracker and also couldn't yet pin it down to some specific tkg customization config.

**Comment by Tk-Glitch** [comment]
I have noticed that after coming back home yesterday. I'm working on it.

**Comment by skeevy420** [comment]
Saw in the log that he's using LLVM8 and I'm on LLVM10.  Nearing the end an up-to-date build of wine-tkg to test that difference and I'll let y'all know how that turns out.  I'll be testing with KSP and DXVK from master if that's fine; I don't have the game in the log.

Have you tried PROTON_NO_FSYNC=1 or played with the WINEFSYNC_SPINCOUNT numbers at all.  

just setting any value to WINEFSYNC_SPINCOUNT globally did exactly that to me the other day when creating any new prefix from proton or wine (from here or anywhere else); already existing prefixes worked, but I only tried Hitman 2 when that was going on.

**Comment by Tk-Glitch** [comment]
It has to do with the FS hack. Disabling it fixes the issue.

**Comment by aufkrawall** [comment]
Thanks. I guess I got confused by the latest HotS update which made it hang with black screen for a few seconds, regardless of the fullscreen hack issue. Of course the idea to recheck with Unigine Valley didn't come to my mind at that time...
