### ISSUE TITLE
proton-tkg: Add option to set ACO as the shader compiler backend

### ISSUE THREAD

**Issue by terencode** [Tk-Glitch/PKGBUILDS#337]
Now that ACO is merged into mesa, you have to set an environment variable to use it. 
It would be nice to have proton-tkg append `"RADV_PERFTEST": "aco",` to `user_settings.py`.
You would  set for example `_use_aco` in proton-tkg.cfg.

**Comment by skeevy420** [comment]
I'd prefer an option to use [this commit](https://github.com/daniel-schuermann/mesa/commit/75f6ade9cbc3c86f83593be1f13dbb85dbffd8a1) from upstream ACO as a config switch like `_useACOdefault="true"`

Nowadays I set it to ACO globally upon boot since it's part of Mesa and set the launch option to `RADV_PERFTEST=llvm %command%` as necessary for Proton.

IMHO, an experimental Mesa feature requiring git builds of Mesa should stay in mesa-tkg and not be a Proton feature switch since there is no way of knowing if the user is using an ACO compatible Mesa or not (yeah, it would do nothing in that instance, but also seems like it could be a source of issues being reported from uninformed people).  

Obviously my position will change on this once Arch ships a version of Mesa with ACO.

**Comment by terencode** [comment]
Yes, maybe it's better for the user to just set a global environment for this use case.
What do you use to do so?

**Comment by skeevy420** [comment]
I use `RADV_PERFTEST="aco"` in `/etc/environment` so it's set pretty early on in startup process.

Here's a copy of my /etc/environment because I have a lot of stuff in it and it treat it like a reference sheet with the commented out lines.

```
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#

## Wine Variables
# Wine Esync/Fsync 
# Fsync falls back to Esync when both are enabled
WINEESYNC=1

WINEFSYNC=1

# Causes lots of issues globally
#WINEFSYNC_SPINCOUNT=100

# Wine PBA
PBA_ENABLE=1

# Wine Large Address Aware
WINE_LARGE_ADDRESS_AWARE=1

# Wine Staging Shared Memory
STAGING_SHARED_MEMORY=1

# Wine Staging Real-Time
#STAGING_RT_PRIORITY_SERVER=90 

#STAGING_RT_PRIORITY_BASE=90

## DXVK Variables
# DXVK Async
DXVK_ASYNC=1

## Proton Variables
PROTON_USE_D9VK=1

PROTON_NO_FSYNC=0

## Vulkan -- only enable one
# Default is normally RADV
# AMDVLK (Manjaro package)
#VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json

# AMDVLK-Pro (TkG package)
#VK_ICD_FILENAMES=/opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd64.json

# AMDVLK-Pro (AMDGPU-Pro AUR package)
#VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json

# RADV (Mesa)
#VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

# AMDVLK Experimental Features
#AMDVLK_ENABLE_DEVELOPING_EXT="all"

## MESA options
## AMD\R600 Debug options
AMD_DEBUG=sisched,nir
#R600_DEBUG=sisched,nir

## AMDGPU Tuning
# AMDGPU 16x anisotropic filtering
R600_TEX_ANISO=16

# Vsync off=0, on=1
vblank_mode=1

# AMDGPU Shader backend 
# aco or llvm
RADV_PERFTEST=aco

## AMDGPU MSAA>EQAA Modes
# Program must use Mesa MSAA for these to work
# Modes named after AMD DX9 MSAA tech manual
# No MSAA
#EQAA=0,0,0

# 2x MSAA 
#EQAA=2,2,2

# 2f4x EQAA
#EQAA=4,2,2

# 4x MSAA
#EQAA=4,4,4

# 2f8x EQAA
#EQAA=8,2,2

# 4f8x EQAA
#EQAA=8,4,4

# 4f16x EQAA
#EQAA=16,4,4

# 8x MSAA
#EQAA=8,8,8

# 8f16x EQAA
#EQAA=16,8,8

## MLAA
# Do Not Enable These Globally
# Jimenez MLAA
#pp_jimenezmlaa=16

# Jimenez MLAA Color
#pp_jimenezmlaa_color=16

## Libstrangle Tuning
# run program with "strangle $program" to use
# Cap FPS for OpenGL/Vulkan programs to 60 FPS
FPS=60

# Force enable VSYNC
VSYNC=1

# Tweak Vuklan/OGL mipmap lod bias for crisper textures
PICMIP=-1

## SDL Tweaks
# Let window manager handle SLD2 compositing
SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=1

## KDE/Plasma Tweaks
# none, adaptive, aggressive
PLASMA_PRELOAD_POLICY=adaptive

__GL_YIELD=USLEEP

```

**Comment by terencode** [comment]
Thanks for sharing!
