### ISSUE TITLE
Battle.net app issue after update

### ISSUE THREAD

**Issue by b3nis** [Tk-Glitch/PKGBUILDS#347]
The Battle.net app crashes on launch after an update (by Blizzard) when trying to start StarCraft II (weridly - Overwatch works flawless, also using Battle.net app).

[Video showing the crash](https://drive.google.com/open?id=1_3kdhLqE9KHSpVdKtFjLD-K_1zdL7U8H)

**Comment by Tk-Glitch** [comment]
Since you say it's recent, I'd say that both SC2 lutris installers are very outdated and don't have the `api-ms-win-crt-private-l1-1-0` and `ucrtbase` workarounds for last week's bnet update breakage.

If you know what I'm talking about and have already done so, please provide a log so we can try and find what's going on.
If you haven't, search for `api-ms-win-crt-private-l1-1-0` + `battle.net` + `wine` keywords on your favorite search engine to find out what's up with these and give the fix a go :)

**Comment by b3nis** [comment]
So weird, without any updates or anything - it just started working again. Saw another person who had the same issue after the same update. Well, all good for now. Thankf for the reply Tk-Glitch!

**Comment by Tk-Glitch** [comment]
Good news! Have fun :)
