### ISSUE TITLE
PBA just rebased to Wine Staging 3.19. May be any more no need the additional patches to compatibility with PBA patches?

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#35]
PBA just rebased to Wine Staging 3.19. May be any more no need the additional patches to compatibility with PBA patches?
Thank you.
https://github.com/Firerat/wine-pba/commits/knobs_and_switches

**Comment by neVERberleRfellerER** [comment]
It seems that 3.19 rebase commit was removed. Now "Rebase wine-staging v3.18" is the last commit. Maybe it was defective so even link from your previous comment edits is not safe to use.

**Comment by Kerrung** [comment]
However, I don’t understand why we need additional patches for compatibility with Wine 3.13, 3.14, 3.17, 3.18 if the PBA supports the newest releases of Wine without it. Why not remove these patches and apply PBA without them?

**Comment by Kerrung** [comment]
Thank you

**Comment by Tk-Glitch** [comment]
@Kerrung As @neVERberleRfellerER said, the patches are applied conditionally. If you're manually setting a custom wine version, for example to get a 3.12 based build, you wouldn't be able to use PBA at all if these patches weren't there. Since that pkgbuild is currently offering such functionality, the patches will stay, and be selected automagically so you don't have to worry about it. About 3.19 and PBA, I've tried to rebase the patchset as well and failed so far. Firerat seems to be following a similar pattern but he also seems more familiar than I am with it, so we'll see.

**Comment by bobwya** [comment]
@Tk-Glitch 

I've successfully rebased my Gentoo wine-pba patchsets for **wine-vanilla-3.19** and **wine-staging-3.19**.
They're at: [Github: bobwya/gentoo-wine-pba](https://github.com/bobwya/gentoo-wine-pba).

**todo**: I've still to add some credit; to you and Firerat... :-)

Successfully tested **wine-staging-3.19** with Fallout 4 (again)!

The "commit directories" are all **wine-vanilla** commits. The wine-staging commits are slightly different - because they are the next **wine-vanilla** commit, that **wine-staging** is rebased on.

Bob

**Comment by Tk-Glitch** [comment]
Actually I should replace it with the original patchset's author.

**Comment by Tk-Glitch** [comment]
https://github.com/Tk-Glitch/PKGBUILDS/commit/9450c914117e27d569ef9a63c05c687a49b33445 :)

**Comment by Kerrung** [comment]
I think that https://github.com/bobwya/gentoo-wine-pba is probably better than Firerat because https://github.com/bobwya/gentoo-wine-pba rebases commits every time Wine Staging rebases , instead of doing rebases with every new Wine Staging release. I am wrong?
