### ISSUE TITLE
linux53 compilation error

### ISSUE THREAD

**Issue by logan001** [Tk-Glitch/PKGBUILDS#360]
It is my 1st time trying to use  53-tkg and as lucky as i am at the end of compilation i get

```
==> Installing linux53-tkg-cfs package group with pacman -U...
ERROR: ld.so: object 'libfakeroot.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

if i enter sudo pass i get to install linux53-tkg-cfs-5.3.7-16  linux53-tkg-cfs-headers-5.3.7-16. kind of afraid to do it.
i choose ryzen cpu and most of the rest are default except for fsync=y/ 28-native/i change performance to scheduli and i think that about all.

**Comment by fluffykittyrevenge** [comment]
Due to the updated base group, trying `sudo pacman -Syu base base-devel` would be my first place to start.

This is a hard one because it can be caused by anything from package mismatches to a sudo/root owned file somewhere in your sources or build dirs to running a game or something with a custom LD_PRELOAD variable like gamemode, etc use...hence my and/or suggestions of reinstalling the base and base-devel groups; wiping your sources, build dirs, and ensuring PKGBUILDS/linux53-tkg/* doesn't have any root/sudo owned files; and/or running `export LD_PRELOAD=` to clear out LD_PRELOAD if anything is set (echo $LD_PRELOAD has nothing there by default on my system and 5.3 builds just fine for me).

**Comment by logan001** [comment]
i always downlod pkbuilds in /tmp
Before 53 i installed 52
i give it another try to 52 and it compiles without any issue

**Comment by logan001** [comment]
nvm seems that it compiled the second time

**Comment by fluffykittyrevenge** [comment]
> nvm seems that it compiled the second time

Cool.

Don't you just love weird ones like this?

**Comment by logan001** [comment]
well i did the export LD_PRELOAD=
and compile it after
and it worked

**Comment by logan001** [comment]
ok. now i get another error

```
error: '/tmp/PKGBUILDS/linux53-tkg/linux53-tkg-pds-5.3.7-16-x86_64.pkg.tar.xz': could not find or read package
error: '/tmp/PKGBUILDS/linux53-tkg/linux53-tkg-pds-headers-5.3.7-16-x86_64.pkg.tar.xz': could not find or read package
==> WARNING: Failed to install built package(s).

```
but i have
```
ls *tar.xz
linux-5.3.tar.xz  linux53-tkg-cfs-5.3.7-16-x86_64.pkg.tar.xz  linux53-tkg-cfs-headers-5.3.7-16-x86_64.pkg.tar.xz
```

**Comment by Tk-Glitch** [comment]
inb4 it's some pacman 5.2 BS

**Comment by Tk-Glitch** [comment]
Should be fixed now
