### ISSUE TITLE
Rocket League, "Ran out of memory" proton-tkg

### ISSUE THREAD

**Issue by VGHS-lucaruby** [Tk-Glitch/PKGBUILDS#398]
While playing RL with the latest proton-tkg my game will crash after a few games with a "Ran out of memory" message any help would be appreciated.

I do believe this issue to be a dxvk issue but I thought I would post it here in case, either it's not or I'm an idiot and missing something obvious.

I have attached an image from the crash, along with my system info as well as the d3d log, if this is a dxvk issue I will move the post there.

Thanks for the help and sorry if I'm being an idiot.

![RL](https://user-images.githubusercontent.com/35069188/69385617-dd536500-0cb7-11ea-930b-cb455b02087a.png)
![Sys Info](https://user-images.githubusercontent.com/35069188/69385618-dd536500-0cb7-11ea-9fa1-9fdbf6c642cf.png)
[RocketLeague_d3d9.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3877243/RocketLeague_d3d9.log)

**Comment by telans** [comment]
See https://github.com/Joshua-Ashton/d9vk/issues/170

Assuming that you have large address aware enabled?

**Comment by Tk-Glitch** [comment]
It's a D9VK issue as the game is using d3d9 and not d3d11.
Many reports of similar issues with D9VK lately so I would try either with an older or newer build. I assume the game used to work fine before?
With your hardware I guess the game runs fine with wined3d, so you could alternatively use `PROTON_USE_WINED3D9=1 %command%` as launch options for the game to use it instead of D9VK.

**Comment by VGHS-lucaruby** [comment]
yeah, Telans I'm using large address aware.
Ok tk as its a D9VK issue ill close this issue in that case and open it on their git repository.
Thanks for the confirmation that this is a D9VK issue.
