### ISSUE TITLE
vkd3d-git PKGBUILD fails to clone repository

### ISSUE THREAD

**Issue by gardotd426** [Tk-Glitch/PKGBUILDS#420]
Issue: trying to run `makepkg -si` in directory `vkd3d-git` just hangs at 
```
  -> Cloning vkd3d git repo...
Cloning into bare repository '/home/matt/gits/PKGBUILDS/vkd3d-git/vkd3d'...

```
Expected Behavior: package installs

Steps to reproduce: clone the repository, change directory into PKGBUILDS/vkd3d-git, and run `makepkg -si`

I've tried it multiple times, on 2 different Manjaro installs, one old one on unstable branch and one fresh install on stable, and on a vanilla Arch install. Same result every time.

**Comment by Tk-Glitch** [comment]
The vkd3d repo can be extremely slow at times. How long did you wait?

**Comment by gardotd426** [comment]
20 minutes. I'll try again and just leave it in the background while I play Doom or something, and I'll post what happens

**Comment by telans** [comment]
Sometimes you just need to stop it and retry, this happens with other repos for me too.

**Comment by Tk-Glitch** [comment]
No matter how much I tried to reproduce this, it always ended up effectively succeeding after a while. Still, that repo is really slow and terrible (just like wine's official repo).

**Comment by Ashraaf** [comment]
Using `git://source.winehq.org/git/vkd3d.git` instead of `http://source.winehq.org/git/vkd3d.git` solved this issue.

I simply added `git://source.winehq.org/git/vkd3d` (without .git) to `_vkd3d_source=""` in customization.cfg and walaaa!!, cloned the vkd3d repo in 1 second.

Probably can make it as the default source? as as both are official vkd3d source.

**Comment by Tk-Glitch** [comment]
Weird that it makes a difference.. But sure that's a viable change.
