### ISSUE TITLE
Suggestion regarding PBA support

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#439]
Since this patch is abandoned by the author, can only be applied to wine 3.19, and D9VK/DXVK & D9adapter are considered to be the defacto go to's for DX9 games I suggest it be removed from the default patch section. There may still be people who use it for a selection of games on older Nvidia cards that don't support the newer Vulkan drivers so I recommend either moving it to the Legacy Section or turning it into a Community Patch so its still available for them.

**Comment by Tk-Glitch** [comment]
I don't think anybody else cared, but I agree.

**Comment by ronoverdrive** [comment]
@Tk-Glitch I was just thinking while I was editing my customization.cfg that it seems like a waste of code in the PKGBUILD to have to detect what version of WINE the user is using for what is basically a legacy patch that very few people use these days. I was gonna suggest just dropping it entirely, but then I remembered a thread where the last time I suggested dropping it someone commented how they still use it.

**Comment by Tk-Glitch** [comment]
Yeah the build system can take it, and the "complexity" it adds is extremely small for PBA, especially since it's kinda locked now and unlikely to change. People with no Vulkan capable hardware and possibly even no G9 might still need PBA. Going forward we'll see how it goes but I think it'll stay around for some time 🐸
