### ISSUE TITLE
[linux54-tkg] [Nvidia] The kernel builds and boots, but cannot start X

### ISSUE THREAD

**Issue by thorsten-passfeld** [Tk-Glitch/PKGBUILDS#443]
Hey, I'm having an issue with running your kernel on my machine. Here are my most important specs:
CPU: Ryzen 9 3900X
GPU: GTX 1080 Ti
Distro: Manjaro
GPU drivers according to nvidia-smi:  Driver Version: 440.44       CUDA Version: 10.2

In the customization.cfg, I've manually added _OPTIPROFILE="2" and _processor_opt="zen2" for system-specific optimizations. When being asked any questions on makepkg -si, I've used the values that were indicated as default to keep it simple and not cause any unnecessary errors out of the box. The PDS scheduler was chosen (which I wanted anyways).

Everything builds perfectly fine, it's being picked up by GRUB, including the kernel headers, etc.
Now the problem occurs when I try to boot the new kernel. The kernel seems to try initializing everything, I could quickly see something fail for a split second, the rest just keeps saying [OK] Something. It then keeps hanging on: “Started TLP system startup/shutdown”

I've tried using CTRL + ALT + F2 to login, which worked perfectly fine. But trying to run "startx" resulted in an unspecific error along the lines of "Connection refused".

So I've done quite a bit of research for the past few hours and could kind of narrow it down to the Nvidia driver version not being compatible out of the box with non-Manjaro kernels or something related to Nvidia-dkms not being compatible with your optimized kernel. That's why I thought "Oh nice, this guy also offers https://github.com/Tk-Glitch/PKGBUILDS/tree/master/nvidia-all "
Before running anything related to your nvidia-all packages, I tried installing dkms from Manjaro to see if running "sudo dkms autoinstall" does anything. Nope, it seems. Not even any output.

So now I'm at the point where I've tried running makepkg -si in your "nvidia-all" folder, but when it of course asked me to replace the currently installed drivers for my backup LTS kernels, I was hesitant and would rather ask you about your advice on here. This is what I just referred to:

> looking for conflicting packages...
> :: nvidia-dev-dkms-tkg and linux419-nvidia-440xx are in conflict (nvidia). Remove linux419-nvidia-440xx? [y/N] y
> :: nvidia-dev-dkms-tkg and linux54-nvidia-440xx are in conflict (nvidia). Remove linux54-nvidia-440xx? [y/N] ^C
> Interrupt signal received

As you can see by my hesitation, I'd rather not make my system unusable, as this is the system I run daily. Honestly, if this is too annoying or risky to fix, I would be fine just running the 5.4.6-2 LTS kernel I run now, because this was just intended for tinkering/fun purposes. Obviously risking making my backup kernels unusable is not an option I'd willingly go with. That's why they are my backup in the first place. :D

I read on the forums that you are running Manjaro yourself. If so, I'm sure you've had this issue yourself before. Maybe you can give me some good advice, as I don't suspect anything to be wrong with your files. They looked perfectly fine to me.

**Comment by Tk-Glitch** [comment]
Sorry for the delay, but yes, using my nvidia-all PKGBUILD should fix it. The Manjaro packages for nvidia will fail to compile on a different kernel than what they are explicitely targeting. Also some driver revisions will need patches to work with a given kernel release, and nvidia-all takes care of this as well. Since you can get to a TTY just fine, the kernel itself seems good.

There's a rule to remember though. The nvidia-all PKGBUILD will patch your driver for kernel compatibility for the kernel(s) currently installed. So if, for example, you were to install the packages while you have 5.4.6 manjaro and 5.4.7 tkg installed, your packages will be patched for 5.4.x fine. However if you then install 5.5rc (or release, later on), you'll be missing the patches for 5.5. So you should always rebuild the nvidia-all packages (even for the same driver version) if you install a kernel from a different major version, and always do it *after* kernel installation.

Also I have been running Manjaro for a little while a few years back on one of my machines but it's not the case anymore. But there's no reason for Manjaro to break what I said above :P

**Comment by thorsten-passfeld** [comment]
Hi there! Thanks for your answer. So you are saying I will definitely be safe replacing linux54-nvidia-440xx with nvidia-dev-dkms-tkg then? There is no risk involved?

**Comment by Tk-Glitch** [comment]
Absolutely. No risk involved. If, *still, for some reason something breaks*, you can easily recover from it by switching to TTY and running `sudo pacman linux54-nvidia-440xx` (optionally followed by `sudo mkinitcpio -P` to be on the safest side) to restore the previous driver set, then `reboot`, and you'll be back on track.

**Comment by thorsten-passfeld** [comment]
I can totally see that working. That absolutely makes sense. Thanks dude! I'll try it after my round of exams. :)

**Comment by Tk-Glitch** [comment]
I'll assume the issue was indeed fixed! I'll reopen if needed.
