### ISSUE TITLE
Build issues when compiling dxvk with mingw

### ISSUE THREAD

**Issue by ptrb78** [Tk-Glitch/PKGBUILDS#497]
When building dxvk with mingw resulting binaries dont have appropriate entry points for procedures i think.
See https://github.com/doitsujin/dxvk/issues/1453#issue-565841569.
What am i doing wrong?

**Comment by Tk-Glitch** [comment]
Was it built with mostlyportable? Because I have faced a pretty interesting breakage myself since the GCC 9.2.1/glibc 2.31 updates and I'm still trying to understand what's going on. On the other hand, if you have used the mingw-on-arch-automator script the problem might be of a larger scale.

**Comment by ptrb78** [comment]
Hi
I used  automator script.

**Comment by Tk-Glitch** [comment]
I have pushed changes to [mostlyportable-gcc](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/mostlyportable-gcc) in an attempt to fix the issue. The automator script pulls in AUR PKGBUILDs and patching them on the fly to use different tooling would be slightly annoying, so mostlyportable was a better target for this specific regression tracking.

Once built, you'll only need to set the path to your mingw-mostlyportable build in your `dxvk-tools/updxvk.cfg` before building DXVK as usual.

Hopefully it'll suit your needs and fix the issue so that I can report the regression upstream.

**Comment by ptrb78** [comment]
I have compiled mingw from mostlyportable-gcc and after that i have built dxvk with it. My dxvk build works now.

**Comment by Tk-Glitch** [comment]
Thank you for confirming, and I'm glad it worked!

So binutils 2.34 seems to be the problem here. I'll have to do more testing to verify that it's the only one and the other regressions were just a result of it (so we could bump back gmp and isl to latest).
