### ISSUE TITLE
[suggestion] Linux TKG for other distros

### ISSUE THREAD

**Issue by nenoro** [Tk-Glitch/PKGBUILDS#539]
Hi Tk 

(i won't talk in french even i'm tempted). So i was wondering as you did for wine-tkg (my savior) is it possible to port the linux tkg kernel for other distros ? I use Gentoo.

thanks in advance for your answer =)

**Comment by ronoverdrive** [comment]
As per TkG's suggestion on the PKGBUILDS github page you could use [BedRock Linux](https://bedrocklinux.org/) to take advantage of pacman & makepkg found in ARCH on Gentoo to use his PKGBUILD scripts. May not be what you're looking for, but its a solution.

**Comment by Tk-Glitch** [comment]
So my plan is to externalize the source preparation step so it could get easily plugged into a different distro package creation process. It's pretty similar to what was done for the wine-tkg build system without the actual *building* part. Due to various quirks found in different distros kernel handling, I prefer to stay on a safer side here. How does that sound to you?

**Comment by nenoro** [comment]
Well if you do that like you did for wine-tkg then yes it will be very cool =)

**Comment by Tk-Glitch** [comment]
While we are not directly supporting every distro out there, source preparation is now distro-agnostic, and we have explicit support for a few popular distros. Closing.
