### ISSUE TITLE
Nvidia failed build for new kernel linux-pds-tkg-haswell 5.7.0-1

### ISSUE THREAD

**Issue by Galcian79** [Tk-Glitch/PKGBUILDS#568]
Tested with nvidia-beta-dkms from AUR and chaotic-nvidia-dkms-tkg as well. 
Both PKGBLD worked fine with manjaro 5.4 stock kernel and linux-pds-tkg-haswell 5.6, so the problem must be in the new kernel package.

**Comment by Tk-Glitch** [comment]
AUR's `nvidia-beta-dkms` won't work without additional patches (because nvidia doesn't offer 5.7 compatible drivers yet), and chaotic-aur packages need to be updated to use the 5.7 patches from nvidia-all.

I invite you to use nvidia-all PKGBUILD, which is what I offer and work on here: https://github.com/Frogging-Family/nvidia-all
It has support for 5.7 and will build packages for your currently installed kernels.

For chaotic-aur issues, see https://github.com/chaotic-aur/infra
For the AUR package, well, that's on the AUR maintainer so feel free to comment on the AUR page.

**Comment by Galcian79** [comment]
Yes. But without a repo It'll be uncomfortable to keep track of every new driver release. It would be much better if every new kernel major update is taken on hold until those chaoticaur-nvidia-dkms get patched.

**Comment by Tk-Glitch** [comment]
I'm no chaotic-aur's maintainer though 🐸 That's why I pointed out the chaotic-aur repo. I'm working on the source here, and what is being made out of it is out of my grasp for the most part. The 5.7 compat patch and related changes were added to nvidia-all on April the 16th so your issue isn't due to me being slow 😄

**Comment by Galcian79** [comment]
> I'm no chaotic-aur's maintainer though  That's why I pointed out the chaotic-aur repo. I'm working on the source here, and what is being made out of it is out of my grasp for the most part. The 5.7 compat patch and related changes were added to nvidia-all on April the 16th so your issue isn't due to me being slow

I know

**Comment by EsdrasTarsis** [comment]
This has already been fixed in the chaotic-aur

**Comment by Galcian79** [comment]
> This has already been fixed in the chaotic-aur

Then it is a very recent patch, because I tested those packages two days ago and didn't worked.
