### ISSUE TITLE
Standalone Origin client freezes at login with "wine-tkg-staging-fsync-vkd3d-git" 5.10

### ISSUE THREAD

**Issue by XaeroVincent** [Tk-Glitch/PKGBUILDS#573]
When attempting to run the standalone Origin client (not Origin opened thru Steam) using wine-tkg from Chaotic AUR repository on Arch linux, Origin gets stuck on the loading screen. Other variants of Wine and Proton, including vanilla Wine 5.10 are able to login and show the program window.

I just see a window that says:
"Connecting to Origin..."

**Comment by Tk-Glitch** [comment]
I have added a workaround with https://github.com/Frogging-Family/wine-tkg-git/commit/7d43c1299f1af51d30458e953641eba963ef6479

You can enable it by setting `_origin_fix="true"` in your .cfg if building yourself.
@PedroHLC might want to be aware of this since I have decided to have it disabled by default due to the performance implications (even though it's just what we already had before, no better nor worse).

**Comment by PedroHLC** [comment]
Ok, thanks, is it also disabled on proton-tkg?

**Comment by Tk-Glitch** [comment]
Yes. I'm hopeful it'll be very temporary and a proper fix will be found.
