### ISSUE TITLE
updxvk fails to build

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#585]
I can build DXVK from a fresh git using the package-release.sh script provided by Doitsujin no problem but, since the comments on Oct 23rd of the DXVK github (54a4e91 & a7de355 respectively) the updxvk script fails to build DXVK on my system. I've tried both Arch's and the mostlyportable builds of MinGW & GCC, nativeopts on & off, PATCHIN 1 & 0 options, removing the dxvk-master folder, and clearing the ccache. I've also tried a full clean git pull of dxvk-tools.

[dxvkbuild.log](https://github.com/Tk-Glitch/PKGBUILDS/files/5501869/dxvkbuild.log)
[updxvk.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/5501873/updxvk.cfg.txt)

**Comment by Tk-Glitch** [comment]
Is your mostlyportable mingw build 8.0.0 based? MinGW 8.0.0 is now a hard requirement to build DXVK.

**Comment by ronoverdrive** [comment]
No it was set to 7.0.0, but it compiles fine with package-release.sh even with my current mostlyportable mingw (one of the things I tried). Will rebuild with 8.0.0 and give it a try.

**Comment by Tk-Glitch** [comment]
Are you sure it's actually building with your mostlyportable build when it succeeds? It could be system-wide mingw (since Arch's package has been bumped to 8.0.0). Updxvk *does run* package-release.sh btw: https://github.com/Frogging-Family/dxvk-tools/blob/527726f275b0ab6bc791e6d24a295d55b1e11765/updxvk#L188
