### ISSUE TITLE
Wine: Faudio not working after 6a44539 commit.

### ISSUE THREAD

**Issue by Suntikka** [Tk-Glitch/PKGBUILDS#64]
I used the get Far Cry 4's audio working with faudio, but after commit 6a44539 audio isn't working anymore. I have faudio-git and lib32-faudio-git installed. Not sure if the issue is with faudio packages or wine build.

I have these settings changed in customization.cfg:
_use_faudio="true"
_FS_bypass_compositor="true"
_proton_fs_hack="true"

**Comment by Tk-Glitch** [comment]
Faudio is WIP, missing stuff, and mostly broken at this stage. The winelib version you can build through wine-tkg-git might also require additional xact libs overrides depending on the game to work at all.

If the game sound was working before 6a44539, it was probably not using faudio, or faudio has been broken upstream maybe.
Since I don't remember FC4 having any sound issue ootb (so without faudio), if it doesn't work correctly with faudio disabled, you should instead try to enable "_staging_pulse_disable", as your issue is very likely pulseaudio related.

Good luck !

**Comment by Suntikka** [comment]
Already tried without faudio and it didn't work. _staging_pulse_disable="true" didn't do the trick either. Welp, I have a working build in opt which should suffice for a playthrough.

Cheers for suggestions though.

**Comment by Tk-Glitch** [comment]
I could add a Faudio package with custom commit and userpatches support if that sounds like a plan to you.

**Comment by Suntikka** [comment]
Nothing against that. :)
If that isn't too much trouble and doesn't make things messy that is.

**Comment by Tk-Glitch** [comment]
Would the latest faudio-git packages work any better at this point in time, or does the problem still persists?

**Comment by Suntikka** [comment]
No difference. But i figured out a fix: Setting xaudio2_7 to native in winecfg works with faudio enabled or disabled. This makes me wonder, is faudio currently considered a native or builtin in wine and did it use to be different?

**Comment by Tk-Glitch** [comment]
@ahmed-elsayed2017 As said previously, the fork works the same way as the optional support in wine-tkg. Basically it's unusable at this point in time except for a couple games. Anyway, the most problematic part is not supporting it in wine, but faudio itself (the current state of the WMA support to be precise).
