### ISSUE TITLE
Need help with wip patch

### ISSUE THREAD

**Issue by ghost-101** [Tk-Glitch/PKGBUILDS#70]
I've been wanting to make a pull request for a GLSL toggle, but could not get what I have working, this is my first patch. The patch replicates the CSMT toggle, it fails at patchinstall.sh. I've tried patching CSMT twice and that exhibits the same behavior on the second patch. I've been testing on 3.16 if that matters.

Use case for disabling GLSL infavor of ARB is to reduce stuttering, and slightly increase framerate. I've found the shader stutter reduction very noticable in DX9 games using wined3d on NVIDIA.
https://github.com/ghost-101/wip-patch/blob/master/GLSL-toggle.patch

**Comment by neVERberleRfellerER** [comment]
Your patch does not really replicate CSMT toggle patch. CSMT toggle patch creates new patch file (it is patch that contains patch) and "extracted" patch is then applied by patchinstall (which is patched to do so). Do you plant to send this patch to wine-tkg-git or to wine-staging? If wine-tkg-git, then you could simplify patch greatly as you would not have to patch patches/patchinstall.sh , but you would just patch staging.c/resource.h/..., basically just remove the top of your patch. The reason why CSMT toggle in wine-tkg-git is overcomplicated is that it istaken from outside instead of being tailored directly to wine-tkg-git. On the other hand, if you want to submit it to wine-staging, you need patch-in-patch.
Now, your patch fails, because e.g. winecfg exists in wine, but patchinstall exists in wine-staging - you are trying to patch both at the same time, which is impossible, since they typically do not exist in single directory structure as they are different projects.

**Comment by Tk-Glitch** [comment]
After giving it a quick look, it looks like the "Local-winecfg-Toggle-GLSL.patch" created is incorrect. Your patch should be creating the file content and doesn't. I'll check it out better asap.

**Comment by ghost-101** [comment]
@Tk-Glitch It's all good, I've took @neVERberleRfellerER's advice on ditching patchinstall.sh and that has worked out. Correcting how the registry keys are set at the moment, the hunk positions also changed.
