### ISSUE TITLE
A request for mesa-git

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#92]
Your builds are way faster than AUR. Could you please consider adding (mesa-git / lib32-mesa-git / LLVM /Clang) to your build?

**Comment by clapbr** [comment]
I see no need for this, I've been using the same scripts for mesa+lib32 for years without a change. The same as AUR's but without nvidia and intel stuff. 
"-git" packages usually only need updates when something breaks (dependency changes, rebuild due to dependency updates etc)
LLVM is a bit annoying to build though so I've been using this binary repo (it is updated daily from latest svn), but llvm8 is very close to stable and when it releases I might build it for the possible march=native optimizations.

> [llvm-svn]
> Server = https://repos.uni-plovdiv.net/archlinux/$repo/$arch

Let me know if you need any help with mesa PKGBUILD, it should be pretty straightforward.

**Comment by ahmed-elsayed2017** [comment]
I've used this binary repo for mesa-git

[mesa-git]
Server = http://pkgbuild.com/~lcarlier/$repo/$arch

But it is not up-to-date and I need the latest vulkan version.

I am building now mesa-git from AUR, and LLVM is being built from more than 3 and half hours, and hasn't finished yet (65%).

**Comment by clapbr** [comment]
> I used this binary repo for mesa-git
> 
> [mesa-git]
> Server = http://pkgbuild.com/~lcarlier/$repo/$arch
> 
> But it is not up-to-date and I need the latest vulkan version.
> 
> I am building now mesa-git from AUR, and LLVM is being built from more than 3 and half hours, and hasn't finished yet (65%).

Now just let it go :D In the future don't bother building llvm every time, as you realized it takes too much time. You can build mesa-git with stock llvm7 from arch repo, just edit deps in PKGBUILD. If you need/want the latest llvm8 I recommend repo I cited above.

**Comment by ahmed-elsayed2017** [comment]
Ok. I will do that next time. Thanks.

**Comment by ahmed-elsayed2017** [comment]
I am sorry. I don't know how to do that!

**Comment by ahmed-elsayed2017** [comment]
LLVM-SVN 8.0 took alone 7 hours to finish.

**Comment by XeonDead** [comment]
You can just enable ccache - by changing the flag in makepkg, doing this (and providing sufficient space for ccache, let's say 50-100GB) will increase build speeds all throughout system.
I can't quite remember but my haswell handles llvm-svn package rebuild in around 2hrs with ccache on. Those builds are gcc -> llvm-svn so that the ccache won't change as much.

**Comment by ahmed-elsayed2017** [comment]
That could be a good idea. Thanks.

**Comment by Tk-Glitch** [comment]
For LLVM : https://www.linuxsecrets.com/archlinux-wiki/wiki.archlinux.org/index.php%3Ftitle=Unofficial_user_repositories&mobileaction=toggle_view_desktop.html#llvm-svn

Not sure if the combination with https://aur.archlinux.org/packages/mesa-git/ would work as is (I honestly didn't check), but that may be all that's needed.

**Comment by ahmed-elsayed2017** [comment]
Thank you all for your help.
